### ISSUE TITLE
Add support for USB storage devices or SD cards as media devices

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1148]
Original [issue 1148](https://code.google.com/p/quodlibet/issues/detail?id=1148) created by nick.boultbee on 2013-04-29T21:48:10.000Z:

USB storage (MSC) devices are often now used as libraries (of sorts) e.g. in cars, TVs etc.

Treating these as media devices would probably be the best integration point (though, actually I've barely ever used this browser); either way copy to device functionality (possibly with transcoding) would be very useful.

**Comment by lordmoocow** [comment]
Just came across trying to get my mass storage device (a media player with an SD card inserted) to appear in the media devices view.. is there a plan to implement this or am I missing a crucial step?

I'm currently using 3.5.1 despite 3.6.1 being available as the Archlinux package hasn't been updated for a while, but seeing as this issue is still open and I can't see anything mentioned in the change logs I am assuming that this hasn't changed.

**Comment by declension** [comment]
Correct. Media / devices support has changed very little in a long time, but I'd like to get _this_ one sorted "some time"...

**Comment by CreamyCookie** [comment]
Closing this since device support was removed.
