### ISSUE TITLE
Document library statistics

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1224]
Original [issue 1224](https://code.google.com/p/quodlibet/issues/detail?id=1224) created by fturco2 on 2013-08-10T08:04:12.000Z:

I'm using QuodLibet 2.4 on Ubuntu 13.04. I noticed that the play count gets incremented even if a song is not played in its entirety. For example, I have a song that is 1:49 in length, and I played it from 0:00 until 1:00, then I paused it and I played another song. The play count for the first song switched from 0 to 1 even if seconds 1:00 to 1:49 were not played. Is this know or expected behaviour? I'd like to increment the play count only if a song is entirely played.

**Comment by j39m** [comment]
Can this issue be closed? The documentation for playcount is up-to-date and the configurable slider is there in advanced preferences.

**Comment by jej** [comment]
> So, totally agree with the change of the status only at the end.

Currently the " certain proportion of the song’s duration" is 50% by default. The @jerigondor78 comment is still pertinent on that point.

Now I set to 100% too, because to me a track is played if 100% is played, else it was partially skipped... Most of the time the tracks are fully played or never played, that's the most important to know. (It maybe usefull to query for partially played tracks, for exemple to do a 2nd listen, but it's another topic)

So this issue may be partially closed 🤓

**Comment by declension** [comment]
PRs still accepted of course and if there's something more specific that needs documenting maybe let's open a separate issue
