### ISSUE TITLE
Stay on a playlist until I select a different one

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1426]
Original [issue 1426](https://code.google.com/p/quodlibet/issues/detail?id=1426) created by solitaire@centurylink.net on 2014-07-15T04:23:14.000Z:

Quod Libet 3.0.2, Linux Mint 17

Problem three of three: (with 1424 and 1425)

When playing a song in a playlist, if I click on a different playlist there is no indication which list has the current track, 'Jump to Playing Song' doesn't jump across playlists, and, when the track ends, control switches to the first track in the second playlist.

Have Quod Libet stay on a playlist until I select a song in a different playlist.

**Comment by declension** [comment]
I don't understand the enhancement here... I think it's confusing enough for users to know about the queue, and the current songlist, so having a third, magic place where songs can come from (the playlist you happened to be on when you double clicked the first song) is a step back in ease of use.

If you want to play a whole playlist you can enqueue it, otherwise I think WYSIWYG has to be the best option.

**Comment by lazka** [comment]
Afair this is what iTunes does, queuing the list at the moment the song starts and using that as a source. I agree that this would be confusing given what QL does today... (we could of course think about switching to a different player source model, but that's another issue)

I've implemented "jump to playing song" now in 0f57b08 so at least it's possible to switch back to the source if needed

-> Closing
