### ISSUE TITLE
ReplayGain plugin: saving progress window is always on top

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1475]
Original [issue 1475](https://code.google.com/p/quodlibet/issues/detail?id=1475) created by joschuaga@yahoo.de on 2014-09-27T10:58:28.000Z:

<b>- What did you try to do?</b>
Just use the ReplayGain plugin on a bunch of files and after they have been analized, I clicked on &quot;Save&quot;.

<b>- What did you expect to happen?</b>
When switching to another window, I expected the progress window to get minimized.

<b>- What did happen instead?</b>
It's always on top / visible, even if I watch a video in fullscreen mode.

<b>- Which version of Quod Libet?</b>
3.2.1

<b>- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid)?</b>
Ubuntu 14.04 / 64 bit

**Comment by julien-f** [comment]
It is annoying, I can't hide it, I can't move it, it simply takes and hides a piece of my screen for a (sometimes) long time.

I believe the issue is that it is declared as a [GTK_WINDOW_POPUP](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GTK-WINDOW-POPUP:CAPS) instead of a [GTK_WINDOW_TOPLEVEL](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GTK-WINDOW-TOPLEVEL:CAPS).
