### ISSUE TITLE
"Edit lyrics" button doesn't work (it opens a website instead)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1485]
Original [issue 1485](https://code.google.com/p/quodlibet/issues/detail?id=1485) created by joschuaga@yahoo.de on 2014-10-31T17:17:25.000Z:

<b>\- What did you try to do?</b>
1. Click Information / Lyrics on a song.
2. Click on &quot;Edit lyrics&quot;

<b>\- What did you expect to happen?</b>
A way to edit the lyrics.

<b>\- What did happen instead?</b>
A website opens. http://lyrics.wikia.com/{artist_name}

<b>\- Which version of Quod Libet?</b>
3.2.2.

<b>\- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid)?</b>
Ubuntu 14.04 / 64bit

**Comment by declension** [comment]
Fixed in https://github.com/quodlibet/quodlibet/commit/949444c516d5a988461d26609fa0c19dd11127ca (renamed the button for clarity).

The idea was you can edit _Lyricwiki's_ version of the lyrics online using that button, but I'm sure most people  use this to _view_ them online.

Editing lyrics happens in-place.
