### ISSUE TITLE
GStreamer: control sink volume directly

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1512]
Original [issue 1512](https://code.google.com/p/quodlibet/issues/detail?id=1512) created by reiter.christoph on 2015-01-01T21:33:58.000Z:

We currently have one extra volume control element for replaygain and app volume adjustment.

This has the disadvantages:

 * Volume adjustments are delayed depending on the buffer size in the sink
 * The sink doesn't know about muting.. but that should be rare I guess.

We could also increase the max-buffer size for pulsesink which could result in less wakeups -&gt; less CPU.

Problems:

With PA in flat-volumes=yes mode the sink volume also adjusts the master volume (master volume is max(client volumes) I think) so we can't save and restore it as we don't want to change the master volume on start.

Preliminary plan:

 * Figure out what other players do (simply don't restore maybe?)
 * At least implement direct volume for all sinks except pulsesink so we get rid of the delay (See issue #1389)

**Comment by atomnuker** [comment]
Would be very nice to have this as an option, as it's a bit awkward to have to use MPRIS or the volume button of the player itself to increase the volume. Think about it this way:
1. User sets pulseaudio sink volume to 100%
2. User uses player control or MPRIS to adjust actual playback volume
3. User reduces overall pulseaudio output sink volume because something else starts playing
4. By extension, with flat_volumes=yes, the QL sink input volume gets reduced.
5. User compensates with increasing player volume using MPRIS/player controls
6. User closes player, does something else which sets the PA sink volume to 100%, reopens player
7. Previous volume memorized by PA gets scaled against current sink volume and set, resulting in a too low volume which the player controls/MPRIS can't compensate for because the PA sink input volume is too low.

PA remembers the sink volume and rescales it to match the current sink volume, which works very well with or without flat volumes. It makes no sense to have this additional abstraction anymore and is becoming more of a quirk to fix a problem which doesn't actually exist. I'd try fixing it myself if the whole volume code wasn't so split up and I knew more python.

**Comment by lazka** [comment]
Fixed in master (and shortly the PPAs). Please give it a try.

**Comment by atomnuker** [comment]
Works fine, except that there's an issue with the mpris volume control. Setting everything to maximum volume, and then sending the player a request to reduce the volume to 1% reduces the volume to 22% in the QL audio widget (and pulseaudio). Setting it to 97% causes the volume in PA and QL to be 99%, so I think those factors of 3 you multiply by in the commit might have something to do with it.

**Comment by lazka** [comment]
Thanks for testing. This is on purpose, the ``** 3`` means to the power of 3 in Python, to match the volume control widgets in pavucontrol and gnome-control-center. A volume factor of 0.01 will display as 0.01 ^ (1/3) = 0.215 in all control widgets.

**Comment by lazka** [comment]
Closing this for now.

In case any problems come up we might have to add an option in the preferences to force software volume adjustment.

**Comment by atomnuker** [comment]
The mismatch is that controlling the volume through MPRIS actually sets the PA sink volume to the logarithm of what's set by MPRIS. Setting volume through MPRIS to 0 still sets the PA sink volume to 0. That 1% to 25%(PA) mismatch is probably caused by that.
Either way, it's not a big deal at all. I don't think there's a need to have separate option to have logarithmic or linear volume, everything works as intended.
Just posting this in case anyone in the future wonders why 1%(MPRIS) -> 25%(PA/whatever AO) happens. Tell them to take a look at how the PA volume changes around 75% -> 100% and it's obvious that it's logarithmic.
