### ISSUE TITLE
mp3: prefer txxx replaygain over rva2

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1587]
In case both are there, prefer txxx, as that's what foobar writes.

**Comment by lazka** [comment]
Also see #1502

**Comment by Moonbase59** [comment]
+1 for preferring TXXX, since I use *metamp3* still for my ID3v2.3-tagged MP3s (TXXX only, no RVAD/RVA2). Due to the conversion to ID3v2.4 I cannot (yet) use QL for RG'ing.

More reasons:
* I broadcast using *IDJC* and IDJC also prefers TXXX over all others.
* Tools like *bs1770gain* (https://sourceforge.net/projects/bs1770gain/) and *r128gain* (https://sourceforge.net/projects/r128gain/) also use text format tags.
