### ISSUE TITLE
Make adding a new radio station easier

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1595]
Currently, the UX for adding a new internet radio station is tricky - it took me a while to find it myself (it's at the very right of the search, under the settings button.

It might be better if we exposed a "+"-like button in the browser UI (i.e. left-hand panel), much as we do in the Playlists Browser and the Audio Feeds Browser.

**Comment by Negirno** [comment]
Also, somehow make the added stations more obvious. I've added Radio Paradise's 192k ogg stream, but I couldn't found it with search because it doesn't seem to have a title tag. I couldn't even search the stream's file name/URL. Luckily, I've found it in the 'No Category' folder in the bottom of the list, and adding the title tag manually solved the issue.

Trying to add the same URL again only displays a warning that it's already in the library, which is confusing to regular users.

My proposed solution to the problem: move that 'No Category' folder to the top, at least under Favorites, and rename it to something like 'New Items' or 'Added Stations'.

**Comment by lazka** [comment]
Radio stations get added to the radio favorites. Everything not in the favorites can be removed when updating the radio list.

For radio adding UX: I was hoping that moving all actions in all browsers would make it more obvious that it's in the menu button. Feel free to add it back.

For post adding UX: Maybe add some transient notification somehow that says "Your radio station was added to favorites. [Switch to Favorites]"?

**Comment by Beast141** [comment]
Hi
I agree with the above. Somehow - when adding a favorite radio station, like the one i added recently, it is an aac link. The name is just a bunch of random characters, i cannot even rename it. i tried adding tags but its not working, can someone help in terms of renaming a radio station favorite??  Please.. otherwise i just have a number of random characters and i dont know which radio station is which!

**Comment by urielz** [comment]
@Beast141 It seems to work fine for me with the latest version of QL (3.7.1). As stated here (http://quodlibet.readthedocs.io/en/latest/guide/browse/iradio.html) the only tags you can edit are artist, title and grouping.

Agree with @declension, the placement of the add radio option is a bit buried in the UI.

**Comment by Beast141** [comment]
omg i kept clicking on the 'tags from path' and 'rename files' under 'Edit Tags' property dialog. Instead i didnt click inside 'Edit Tags' tab.
I renamed my radio station! thank you

**Comment by nodiscc** [comment]
I think adding an `+ Add New ...` button below the left panel would be useful, and consistent - the Audio Feeds browser already has an Add New button placed there:

![cap](https://cloud.githubusercontent.com/assets/3950390/23171463/da0adcb0-f852-11e6-9909-4c5a9d078c00.png)

**Comment by declension** [comment]
Fixed by #4076
