### ISSUE TITLE
Restore queue layout at start-up

### ISSUE THREAD

**Issue by d9h02f** [quodlibet/quodlibet#1605]
The queue pane thing is always folded in when Quod Libet is restarted, regardless of what it looked like before and even if the song list is hidden. Folding it out again doesn't restore the previous look either, it just maximises to the available space.

QL 3.4.0 but I think this has always happened.

**Comment by d9h02f** [comment]
Just bringing this up again as I hope it's only a small enhancement.

**Comment by Jimi-James** [comment]
I want this feature, please. I've been using a hacky solution where a script runs quodlibet --queue=t and then quodlibet --queue=on to make the queue show up on start, but that workaround has always had really annoying bugs. In the most recent versions, I've come to realize it doesn't even work anymore. Nowadays, with that script, it still always starts up with the queue minimized. What's worse, is my "workaround", just as recently as when it stopped working, has caused a bug where half the time QL starts up, my queue is replaced with my entire song list.

**Comment by CreamyCookie** [comment]
I would be interested in having this fixed, because I always set the queue size to about half of the window after opening it.

I think one would have to store and restore the [`allocated_height`](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.get_allocated_height) of the [`QueueExpander`](https://github.com/quodlibet/quodlibet/blob/e7cf5016dc1d0e2945186d5d71a585a37ff385cf/quodlibet/quodlibet/qltk/queue.py#L60).
