### ISSUE TITLE
Make album-heuristics consider date-tag

### ISSUE THREAD

**Issue by funkyfuture** [quodlibet/quodlibet#1613]
in #1576 i proposed to consider the date of an album when heuristics figure out.
This seperates correctly in case of different releases with a common name like _In Dub_, _Unplugged_ or other releases with identical name.

this was closed with two arguments:

> We've added "albumartist" for this some time ago. Wouldn't that be enough?

you can't expect every user to tag their collection with the same schema. in that case you wouldn't need heuristics at all.
also, yes [this happens](http://www.discogs.com/artist/10263-David-Bowie), there are different releases with same albumartist and release title.

> I'm worried that this makes it harder to merge tracks in case of not fully tagged libraries and "date" being used as recording time and not the release time in some cases.

can you please elaborate that scenario. i don't get it.

**Comment by danielkza** [comment]
> you can't expect every user to tag their collection with the same schema. in that case you wouldn't need heuristics at all.

That argument also applies to using the date. What if I put the original song release date, instead of the album date, in that tag? It will split up pretty much every single song into it's own album.

Album artist is deliberately defined to apply to the whole album. That's why it makes perfect sense to use it. For it to make sense to give another tag that same treatment, it also has to clearly be targeted at the album. Currently the easiest way to fix things is to tag files using Musicbrainz, that assigns unique UUIDs to each release. Quodlbet also understands tags for release codes (`asin` and `barcode`), but I don't think they are currently used for album separation.

**Comment by CreamyCookie** [comment]
For making splitting easier there is #2193

Closing this as `won't fix`. Thanks for the report though!
