### ISSUE TITLE
--print-query gives "timeout" errors

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1616]
>>> quodlibet --print-query='&(~mountpoint="/media/Elements",|(x=/.+/,xx=/.+/,xg=/.+/,xt=/.+/))'
    timeout
With exit code 1. 

It used to work fine. 

It works if 
- used in QL user interface
- used in another instance of QL in another PC but with a library very small (the big one has over 55k tracks)
- I get rid of at least one of the conditions, such as

    ```quodlibet --print-query='|(x=/.+/,xx=/.+/,xg=/.+/,xt=/.+/)'```
    ```quodlibet --print-query='&(~mountpoint="/media/Elements",|(x=/.+/,xx=/.+/,xg=/.+/))'```

Using QL 3.4.99+7334~43bdd3f-0~ppa0~precise on Ubuntu 12.04.

**Comment by declension** [comment]
I assume `x`, `xx`, `xg` are all custom tags of yours?

Unsurprisingly, having just tried, I can't replicate this behaviour, even when substituting better-known tags etc, but then the library I'm testing on is ~9k not 55k. But it doesn't strike me as _that_ bad that a complex query like that runs slowly on that size of library.

Out of interest, have you tried using terms like `x=!""` or `x=/./` instead of `x=/.+/`? Off the top of my head I think the latter will compile to an equivalent pattern and the former will probably be slower,but it's worth a try.

Do you want to treat this as a bug (i.e. "it shouldn't be timing out at all" / timeout should be longer), or a request for performance improvement (which will be a lot harder)?

**Comment by spxxxk** [comment]
These are custom tags and seem to be the culprits here since the command below works fine even though it returns more results (well, all of them).

    quodlibet --print-query='&(~mountpoint="/media/Elements",|(genre=/.+/,date=/.+/,artist=/.+/,title=/.+/))'



Same result with ```x=!""``` and ```x=/./```.

>But it doesn't strike me as that bad that a complex query like that runs slowly on that size of library

It used to work fine, so I thought something changed. Could always be my machine getting tired...
And execution time always was like a fraction of a second, 

"Timeout" error seems to appear a second after execution. If it's intended I'd definitely vote for a longer one !

Performance is quite impressive actually (in QL UI for the above pattern) so I wouldn't say improving it is a priority.

**Comment by lazka** [comment]
It could also be that en error occurred while executing the query. Open the primary instance in a terminal and check if there are any error messages printed there while executing your query in another one.

Regarding the timeout, increasing it should be fine.

**Comment by spxxxk** [comment]
No error messages printed whatsoever. Even with the ```--debug``` flag.

Something new I just found, the same command but switching the 2 ```AND``` conditions is working fine. Maybe that search pattern is faster to execute.

    quodlibet --print-query='&(|(x=/.+/,xx=/.+/,xg=/.+/,xt=/.+/), ~mountpoint="/media/Elements")'

**Comment by lazka** [comment]
I've increased the timeout now (PPA should be ready)

**Comment by spxxxk** [comment]
Working now, thanks.

Weird that a search feature is that much limited in time, but it looks the fifo timeout parameter doesn't only affect that command line, so I'll let you be the judge to know what's good for everybody, if you wish to bring it back to 1s.

**Comment by lazka** [comment]
Thanks for testing.
