### ISSUE TITLE
audio cd playback

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#163]
Original [issue 163](https://code.google.com/p/quodlibet/issues/detail?id=163) created by lmello.009 on 2009-03-25T03:40:59.000Z:

I tried the 'media devices' view, with an audio cd inserted, but nothing
appeared. Is playing audio cd's supported at all, or maybe there's some
incompatibility with my hardware (it's a TEAC DVW28SLC)? Other cd players
work...

**Comment by moebius1** [comment]
Bonjour,

I think that reading cd capability would be nice ; In quodlibet there's an file browser, so why not add a cd-rom entry ?

Well, I say that because I use quodlibet for dance learning music (nice feature that tempo change ! ); sometime, a teacher come with a CD and says : « well I'm going to teach you a dance ; would you please set up the 5th track of this CD ? »
I say yes and launch rhythmbox (no tempo change anymore :(  )on my poor old laptop with its poor 1Go memory, just for readind this  bloo.. cd, is that fair ? If I could do everything with just Quodlibet, it would be very nice...
I'm not really knowing what kind of work is necessary to put in this feature but I suppose there's a lot of libraries that could be put in quodlibet with not too much pain ?
If it's the case, please do, We are numerous that would be very grateful for this, I'm sure ! If it's just an ideological choice, It seems that «quodlibet» means « as you want» isn't true ? :)

Just another thing (please don't try to kill me) it would be nice if Quodlibet could read audio track of any video...but it's another story !

cordialement,

Moebius

**Comment by lazka** [comment]
Imo this is out of scope for QL. Multiple problems:

1) I don't own a CD so I can't test things
2) CDs are different from everything else and need special handling
3) QL wont add any special value for CD playback

I'd suggest:

* Try VLC (it also has speed adjustment, see View>Status Bar)
* Rip your CDs and then play them with QL
