### ISSUE TITLE
documentation for OS X build process?

### ISSUE THREAD

**Issue by glyph** [quodlibet/quodlibet#1648]
I downloaded quod libet's code, but it's not clear to me how to transform it into a working Mac application so that I can work on it on my local machine and make contributions.  I'm hoping this ticket will just be closed by saying that I didn't read something, but `setup.py build` just produces a bunch of errors.

**Comment by lazka** [comment]
1) I'm currently working on improving this.

2) It is currently possible to run everything without installing/compiling by 
doing the following (this doesn't make it easy to add new dependencies, but 
that's rarely needed)

  * Download/Extract Quodlibet-3.4.0_1.zip
  * git clone quodlibet..
  * Copy Quodlibet.app/Contents/MacOS/QuodLibet to e.g. Quodlibet.app/Contents/MacOS/Run
  * In the last line of Run, replace with ```$EXEC "$PYTHON" $*```
  * ./Quodlibet.app/Contents/MacOS/Run <path_to_git_clone>/quodlibet/quodlibet.py
  * ```setup.py test``` fails that way afair due to CWD changes in the launcher script, I still need to look into that.

**Comment by glyph** [comment]
Thanks!

Also curious; are there plans to codesign the official builds of QL?

**Comment by lazka** [comment]
I've opened #1649 for that.

**Comment by lazka** [comment]
* Updated devel guide: https://quodlibet.readthedocs.org/en/latest/development/index.html
* New section about creating a devel environ: https://quodlibet.readthedocs.org/en/latest/development/devenv.html
* All the scripts for creating a bundle are now in the main repo including documentation: https://github.com/quodlibet/quodlibet/tree/master/osx_bundle
* A new bundle is out (including wma/opus/wavpack support): https://quodlibet.readthedocs.org/en/latest/downloads.html#macosx

**Comment by glyph** [comment]
Thanks again!
