### ISSUE TITLE
Some mp3 files have wrong duration

### ISSUE THREAD

**Issue by gui-don** [quodlibet/quodlibet#1655]
**What did you try to do?**
**What did you expect to happen?**
**What did happen instead?**

Some albums in my collection contains .mp3 files with absurdly long duration when I open them with Quod Libet (for exemple, 119:13:26, which is several days). The problem is, it’s not only the display. The navigation bar is unusable because of that.

![screenshot](https://cloud.githubusercontent.com/assets/1037958/8989193/e59c683a-36ea-11e5-947e-3722de318c56.png)

It only happens with specific files, so I admit it may be a problem related to them. However, the time is fine with other players (totem, rhythmbox or mpv).

**Which version of Quod Libet?**

3.4.1 on Archlinux. 2 plugins enabled : Inhibit Screensaver and Animated On-Screen Display.

**Comment by lazka** [comment]
Can you send me one file? -> reiter.christoph@gmail.com

**Comment by lazka** [comment]
Thanks again.

They both contain TLEN tags containing those huge durations.. not much we can do.
Do you know how these files were created by any chance?

See https://quodlibet.readthedocs.org/en/latest/guide/faq.html for a workaround.

Since this comes up from time to time we should probably add a "MP3 Length Fixup" plugin which just deletes the TLEN frames and reloads the file.

**Comment by gui-don** [comment]
The workaround works. Thanks for your help.

I’m not sure, but I remember seeing something like “encoded with [Max](http://sbooth.org/Max/)”. It uses LAME and is not maintained since 2009.

I think a light plugin could be a good idea. The workaround may be simple but it’s not so easy to find.

**Comment by lazka** [comment]
Reopening until the docs/FAQ are updated as well.

**Comment by lazka** [comment]
Docs updated. Closing.
