### ISSUE TITLE
Docs: explanation for "write" column

### ISSUE THREAD

**Issue by lorentrogers** [quodlibet/quodlibet#1735]
Perhaps this is two different issues, but I think the "write" column in the Edit Tags dialog needs explanation in the docs. (Or I'm just not seeing it...) What exactly does this mean? 

It looks like this is being set for editable/uneditable files:
https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/qltk/edittags.py#L462
If so, what are the conditions for it being uneditable? I assume there are non-supported file formats, possibly corrupt files, wrong file permissions, etc. that could all cause this. This should probably be clarified somewhere.

Also, if the key symbol does indeed indicate Uneditable, then perhaps this should be changed to a lock symbol? (A key seems like the wrong metaphor.)

**Comment by lazka** [comment]
"editable" in this case is just some gtk+ state to mark the cell not editable and a visual difference can be seen.

I think (before my time) the "write" name references that you can click the icons and exclude them from being written. This came up in some other issue where the plan was iirc to just remove the ability to click the icons and remove the column title.. So the icons just show if an entry was edited/removed/added or it can't be changed due to some format restrictions (maybe add a tooltip there as well..)

Does that sound like an improvement to you?

**Comment by lazka** [comment]
The write column is an an indicator only as described above for some time now.
