### ISSUE TITLE
Sudden Crash

### ISSUE THREAD

**Issue by Weej1** [quodlibet/quodlibet#1808]
hi, 
I was running the audio pitch plugin and I happened to right click on a file and got the crash (attached) I wonder if there's any link when I play around with the plugin and the seekbar going out of sync too? 
[Dump_20160204_203544.txt](https://github.com/quodlibet/quodlibet/files/117690/Dump_20160204_203544.txt)

**Comment by lazka** [comment]
The seek bar getting out of sync with the plugin is a known limitation.

Not sure how this attached error is possible.. maybe starting QL mid-apt-upgrade.
I haven't seen similar reports since then, maybe this was fixed due to some other changes in the meantime.

Thanks for the report and providing the trace!
