### ISSUE TITLE
Update Radio streams list

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1822]
The radio streams, which are [downloaded](https://github.com/quodlibet/quodlibet/blob/6b26f4fe3c72df0b9270a3a1f24baffb46908456/quodlibet/quodlibet/browsers/iradio.py) from http://bitbucket.org/lazka/quodlibet/downloads/radiolist.bz2 aren't up to date any more. I don't know about the others, but SomaFM changed their URLs; for example: https://somafm.com/deepspaceone/directstreamlinks.html

Here are the new radio stream URLs: http://somafm.com/SomaFM.m3u

It's a cool feature to provide radio streams, but it also seems hard to maintain.
If it will be maintained in the future, maybe it should be added to this repository. The new radiolist URL could then be: https://raw.githubusercontent.com/quodlibet/quodlibet/master/radiolist.bz2

**Comment by lazka** [comment]
di.fm should also be blacklisted as the free versions no longer stream music.

**Comment by CreamyCookie** [comment]
@lazka Maybe we could use the [Community Radio Station Board](http://www.radio-browser.info/gui/) as a replacement. They have an [API](http://www.radio-browser.info/webservice) and offer [backups of the whole database](http://www.radio-browser.info/backups/).

**Comment by lazka** [comment]
Updated now

**Comment by 2SI3NX** [comment]
[DI](http://diforfree.org/online.php).  You're welcome! You can add any individual streams in QL yourself or add all the streams to QL if you want @lazka 
However, id like to ask something else. @lazka is it possible you could somehow add like a live status column, eg. what is playing right now or any 'shows' in each and every stream. Im trying to add a column like "Album" next to **artist**, or something that will show the live track that is playing, or if any radio 'shows' are playing at any moment but i cannot find any option that will show that. Do you know what i mean?

![selection_012](https://user-images.githubusercontent.com/10450920/32386253-38e12390-c0c9-11e7-848c-47b3c437b46b.png)

**Comment by 2SI3NX** [comment]
Actually, you wont be able to check for live tracks and whats playing, because di.fm has switched to on-demand playback lately. So everytime you switch to a different station and back to the original one, a different random track starts playing from the beginning.
However it would be nice to have 2 features on QL.

1. The thing i mentioned in my first comment, having a live view of what shows are busy playing. Whats "now playing", you can filter find the date and the string "now playing" from the original di.fm
[Source](view-source:https://www.di.fm/calendar) and somehow add this feature as a second "Header", unless this already exists and i cannot find it in QL?

2. A "next" track button could exist when listening to one of the di stations, so that you dont go back and forth just so that a track can change. DI havent released any feature like that. However, the di4free site doesnt seem to have the on-demand playlist thing like di.fm. Its confusing. but they are the same stations, because when a show starts, its the same on both.
