### ISSUE TITLE
Add Repeat-One feature

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1836]
Currently only the whole playlist can be repeated. It’s common to be able to have `Repeat All` and `Repeat One`.

This could be done using three states: `No Repeat`, `Repeat One` and `Repeat All`, the `Repeat All` icon is mostly the repeat icon with a one-symbol, something like this:

![Repeat-One-Icon](https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_repeat_one_48px-128.png)

Repeat-Off could be the `Repeat All`-icon greyed out.

The inactive shuffle-icon should be greyed out then as well.

**Comment by timpulver** [comment]
![repeat-shuffle-icons](https://cloud.githubusercontent.com/assets/1055819/13198321/1e0d1ff4-d806-11e5-9570-7432650de5b8.jpg)

**Comment by lazka** [comment]
This was also proposed in #1411 and it looks good to me. I know you never got a summary there as requested.. I'll try to make one.

**Comment by timpulver** [comment]
The `Repeat One`-icon can definitely not be used, I just put a «1» in there to make the meaning more clear. The gtk+ icons include all the icons needed.

**Comment by urielz** [comment]
I second this idea. I missed this feature.

**Comment by fontealpina** [comment]
Also for me this is a significant lack. 
So far I tried to remedy with Track Repeat plugin but it is too tricky for me.

**Comment by declension** [comment]
Turns out this _was_ there all along ([`OrderOneSong`](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/qltk/playorder.py#L176)), if you worked out to select it as a play "shuffle" order, enable shuffle, and also enable the repeat button.

However at some point, on further digging, this got filtered out as it wasn't designated an `is_shuffle` Play Order (maybe around d782ec3b12e5e309aca2433ecd54c6308ba3b94d) and we're here now. Anyway, it should be closed by #2043 some time soon...
