### ISSUE TITLE
Music —> Open Browser —> Album List vs. Album Collection

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1843]
Both look quite similar to me. Is somebody using any of them?
Pop-out-windows mostly do not feel very good imo. Are they really needed? Why not hide them in advanced preferences so the general UI gets cleaner?

**Comment by urielz** [comment]
I use Album List a lot. I usually find myself browsing the library while listening to music. If you don't use the queue (which I usually don't) this is the only way to don't interrupt the music flow. 

I also don't see this as pop up window (what's is lacking right not though is the ability to switch between the main window and this other alternate view via a hotkey (the usual Command + ~ for OS X users)

**Comment by lazka** [comment]
> Both look quite similar to me. Is somebody using any of them?

"Album Collection" is indented for users who like the album list view but have very large libraries. Not sure if there are many users...

>  Pop-out-windows mostly do not feel very good imo. Are they really needed? Why not hide them in advanced preferences so the general UI gets cleaner?

Which pop-out windows do you mean?

**Comment by timpulver** [comment]
>Which pop-out windows do you mean?

`Album List` as well as `Album Collection`open in a new window.

**Comment by lazka** [comment]
> >Which pop-out windows do you mean?
>
> `Album List` as well as `Album Collection`open in a new window.

Ah ok. The use case there is to allow tag editing in other views while using the main view for playback. And to allow playlist managent by either dragging from other browser windows to the playlist view or the other way around.

**Comment by declension** [comment]
I use additional browser windows for various workflows including the ones @lazka mentioned. They're arguably QL's equivalent of tabs in browsers.

As for the browsers themselves, Album Collection feels (to me) like the least popular; Album List is well loved though (anecdotally - I seem to remember proposing anonymous usage stats for this purpose at some point, should raise an Issue...). There are a couple of alternative / updated Album Browser implementations floating around in patches / PRs / forks / discussions too which should be the place to improve these.

Suggest we close this one unless there's any concrete implementation needed here.

**Comment by declension** [comment]
For usage stats, see #1848.

**Comment by timpulver** [comment]
Okay, seemed to me as nobody was using them, but I was obviously wrong… :)

**Comment by ned2** [comment]
I exclusively use the Album List view and also have a reasonably large library (~1100 albums). I don't think I've tried Album Collection before. I gave it a go, and thought it was going to be useless due to the fact that it was aggregating albums over the `~people` tag, which leads to albums being duplicated across all kinds of names I don't associate with as being responsible for the album (eg values of the composer tag and compilation albums, or albums that feature another artist on a single track.) Then I discovered that you can customise the tag to aggregate over (artist is what I'm after) and use the merge option to de-dupe albums that feature various artists by putting them in a "Multiple Artist Values". Perfect -- I can see myself using this view. Perhaps this would make a more intuitive default.
