### ISSUE TITLE
Album List: Group problem

### ISSUE THREAD

**Issue by ochurlaud** [quodlibet/quodlibet#1871]
In Album list, albums are sorted by artists. However if two artists have albums with the same names, they are grouped in the same item, at one given artist name.

For example:
Duran Duran - Rio
Keith Jarrett - Rio

are grouped as a unique album, sorted with Keith Jarett.

**Comment by declension** [comment]
Yes - see [the FAQ entry](http://quodlibet.readthedocs.org/en/latest/guide/faq.html#i-have-two-albums-with-the-same-name-which-are-merged-in-the-album-list) for why, and workarounds.

**Comment by ochurlaud** [comment]
I read that... It's however a wrong behavior, isn't it?

**Comment by declension** [comment]
Yeah, it's not good... but AIUI it's not a simple fix.

Remember that since albums can have many artists (compilations, classical), it is often _correct_ to merge these based on album name, if that's the only album identifier left - you wouldn't want your compilation CD split into 18 albums...

Personally I use `albumartist` where appropriate, and always add Musicbrainz tags anyway, which means this problem goes away completely.

However it would be good to have something better working (or at least _explained_ to the user) for these common cases, so leaving this issue open (there are some similar older ones somewhere, I think)

**Comment by ochurlaud** [comment]
Yes I see. I never use Musicbrainz tags... Good to know. Thanks for the feedback

**Comment by lazka** [comment]
The FAQ should should be updated to only mention albumartist and musicbrainz.

**Comment by lazka** [comment]
I've updated the docs a bit.

**Comment by lazka** [comment]
> However it would be good to have something better working (or at least explained to the user) for these common cases, so leaving this issue open (there are some similar older ones somewhere, I think)

The only thing I can think of is adding two context menu entries for "Merge Albums" (remove conflicting tags) and "Split Albums" (calculate the distance from the current dir to the most common base dir and if there are two split and add an albumartist to the one where the same artist is in all songs)

**Comment by lazka** [comment]
Trying to implement the above in a plugin would be a good start I think.

**Comment by CreamyCookie** [comment]
Closing this as there is now #2193 regarding the Merge / Split Album feature.
