### ISSUE TITLE
(Replay) Gain adjustments are not applied during the first split second of a song

### ISSUE THREAD

**Issue by kaffeeundsalz** [quodlibet/quodlibet#1905]
I have supplied most of my albums with ReplayGain values and have also set a fallback gain of -9.0 dB in the preferences. However, it seems to me that after starting playback, there is a short delay before Quod Libet applies any of these gain adjustments. In my case, this leads to the first split second of a song being played back considerably louder and followed by a sudden volume drop.

I can reproduce this phenomenon in automatic, album and track mode. It obviously happens only on manually starting playback, not when Quod Libet jumps to the next song automatically, e.g. when one song ends and QL plays back the next item in the queue/song list.

QuodLibet 3.6.0 with OS X 10.11.4 El Capitan

**Comment by lazka** [comment]
Thanks. Is this a new problem?

**Comment by kaffeeundsalz** [comment]
No, I observed this in 3.5.x as well. Just couldn't investigate the problem earlier.

**Comment by lazka** [comment]
OK, thanks.

**Comment by neersighted** [comment]
Also seeing this issue on Windows 10 with QL 3.6.0, but not on Arch Linux...

**Comment by wbiller** [comment]
I've set the standard gain and the pre gain to 6.0dB lately (was 0.0dB) and this is gone, or at least I can't hear any difference anymore.
tested on both systems osx and windows.

**Comment by freezelty** [comment]
I am using 3.8.1, and tried a certain latest 3.9 development version on OS X 10.11.6 El Capitan. They both have this issue. 

I have tried to learn and write a plugin to pause/mute and wait for a short time (for ReplayGain to be applied) then start to play, as a workaround:

```
import time
import threading

from quodlibet import _
from quodlibet import app
from quodlibet.plugins.events import EventPlugin

class MyPlugin(EventPlugin):
	PLUGIN_ID = 'myplugin'
	PLUGIN_NAME = _('Gap before play')
	PLUGIN_DESC = _('Mute about .2 second when songs start.')
	
	_enabled = False
		
	def _sleep_gap(self):
		time.sleep(.1)
		app.player.seek(0)
		time.sleep(.1)
		app.player.paused = False
		app.player.mute = False
		
	def sleep_gap(self):
		threading.Thread(target=self._sleep_gap).start()
		
	def plugin_on_changed(self, songs):
		app.player.paused = True
		app.player.mute = True
		if songs is not None and self._enabled:
			self.sleep_gap()
			
	def plugin_on_song_started(self, song):
		app.player.mute = True
		app.player.paused = True
	
	def enabled(self):
		self._enabled = True
		
	def disabled(self):
		self._enabled = False
```

With this script, the issue seems "suppressed". And all the threading, (repeated) mute/pause/sleep/seek on `plugin_on_song_started` and/or `plugin_on_changed` seem necessary. 

After all my tries, I think maybe this issue happens because "ReplayGain" is applied by a second thread? 

Besides, "Fall-back gain" has no effect, therefore I think the recognition of "ReplayGain" is fast but applying is slow. Also, in my case, the loud songs need about -10 dB ReplayGain, so if the "Pre-amp gain" could be set to +10 dB then maybe the difference will not be heard.

**Comment by lazka** [comment]
Sorry that this took so long :/
