### ISSUE TITLE
Arch package unmantained

### ISSUE THREAD

**Issue by felixsanz** [quodlibet/quodlibet#1906]
The official arch package under extras is out of date for more than 2 months. Is someone able to take care of it? I wish but i'm not familiar with aur or python at all

**Comment by lazka** [comment]
Eric's last package update [0] is also 2 months ago, so he might be busy with other things.

I guess the two options are to:

* Ping him, https://www.archlinux.org/people/developers/#eric
* Offer help with packaging, not sure how that works with Arch.

[0] https://projects.archlinux.org/svntogit/packages.git/log/?qt=author&q=eric

**Comment by ArchangeGabriel** [comment]
It’s way worse than that. Eric has tons of packages that are outdated (https://www.archlinux.org/packages/?sort=flag_date&maintainer=eric), some for months or years, and it was even worse two months ago before his inactivity was bring to the ML (because of wget outdated for months), making other devs package things instead of him.

Indeed, a comparison of:
https://www.archlinux.org/packages/?sort=-last_update&maintainer=eric
with:
https://www.archlinux.org/packages/?sort=-last_update&packager=eric
shows us that he isn’t the one who took care of his packages last months.

He also have a fair share of assigned issue: https://bugs.archlinux.org/index/proj1?do=index&project=1&string=&search_name=&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=snowman&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=&order=dateopened&sort=asc

I’ve tried to call for his resignation or at least a statement about his availability, but the only effect was for other devs to take care of his most important packages.

The bad thing for quodlibet is that unless you are part of Arch devs, which you can’t join just like that, you can’t help with packaging.

Maybe it’s time to call for his resignation again.

**Comment by lazka** [comment]
> The bad thing for quodlibet is that unless you are part of Arch devs, which you can’t join just like that, you can’t help with packaging.

Would a PKGBUILD patch help maybe?

**Comment by ArchangeGabriel** [comment]
Yes, it would, because another dev could then just take it and package it.

I think the main changes (outside usual stuff like version number) are dependencies changes listed [here], right?

[here]:https://quodlibet.readthedocs.org/en/latest/packaging.html

**Comment by lazka** [comment]
> I think the main changes (outside usual stuff like version number) are dependencies changes listed here, right?

yes

**Comment by pierremoreau** [comment]
I wrote an updated [PKGBUILD](https://gist.github.com/pierremoreau/c65646ec1c2cb03e8f88301d18ae6a1e). The second `setup install` to get the plugins in a different package is ugly, but it works.

**Comment by lazka** [comment]
There have been some updates from someone else now: https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/quodlibet

But no one seems to look at our packaging page since most dep updates are still missing... same is true for debian. Maybe putting the packaging changes at the top of the changelog will help...

Somewhat related: master now has a "Check for Updates" menu item. My hope is that it will (1) make people notice new versions faster and (2) force people to get active, be it the maintainer or a user.

Anyway, I'm not sure what to do here (from my side)... If there is anything I can help with, please say so.
