### ISSUE TITLE
Support for Tidal and Spotify etc.

### ISSUE THREAD

**Issue by am4c130d** [quodlibet/quodlibet#1911]
With the growing reliance on streaming sources as an alternative to buying/downloading music, is there any plan to add sources such as Tidal and Spotify?  While there are native players, nothing sorts music as well as QL, and the native players, at best, are horrible for large local music collections.  My goal would be to have the albums/artists I've added as "favorites" available as albums/artists in QL, and playlists to playlists.

Browsing/searching would be great, but, personally, would be of secondary importance to having a single music player play everything.

Thanks

**Comment by lazka** [comment]
spotify has deprecated the apis needed for playback (after 4 years of no updates), so I wouldn't want to put time into something which could be gone tomorrow. Tidal I don't know.

I don't use spotify/tidal, so not sure how any other integration might look like.

**Comment by am4c130d** [comment]
Understood.  There is a Tidal plugin for Kodi - it works well, but doesn't integrate to the Kodi library.  I don't know if they used public APIs or reverse engineered it.

Either way, I do understand your position - its something that would be great to have, but to your point, if its a moving target, its too hard to maintain.

Thanks

**Comment by declension** [comment]
Spotify support is tracked in #751 (and there was a fork at some point with a tentative PR, but a lot of blockers to this happening as above and beyond).

Tidal - what @lazka said really... 

Soundcloud support is something I'm working on, see #1828. Still a fair way to go, but some patterns are emerging that could be helpful later (or not)

**Comment by Negativland** [comment]
If it's implemented on day, please make those services/providers optional for those who don't use them (as plugins for example). 
One of the big reason I use Quodlibet is because I know exactly what it does and what it does not (ex: weird suggestions based on my listening habit,  downloading lyrics I don't care about,...). :-)
For me, the elegance of this project is the streamlined approach of the (local) library manager, tied to the player &  the tag editor, nothing more.

That said plugins are welcome (and I'm using a bunch of them!).

**Comment by lazka** [comment]
The spotify api still does previews only and afaics there is no official/supported tidal api. Closing this. If there is any new development in this area feel free to restart/continue this discussion.
