### ISSUE TITLE
Calculations in a #() Term

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#198]
Original [issue 198](https://code.google.com/p/quodlibet/issues/detail?id=198) created by sp4zzpp2 on 2009-05-03T15:05:34.000Z:

I'd like to see quodlibet to be albe to search something like this:
# (lastplayed &lt; mul(1-rating,5) days)

&quot;mul&quot; represents a multiplication function with 2+ parameters

**Comment by pschwede** [comment]
bump

**Comment by declension** [comment]
Whilst I still think this is an "interesting" feature piece, I'd like to collect people's actual (real-world) use-cases here, i.e. what kind of queries, and operators would be useful (and for what kinds of tags and libraries)

This way, we can make sure we're not missing part of a bigger picture, and so that we can address any quick wins before implementing what could quickly turn into a (slow) generalised numerical expression parser with an awkward, non-infix syntax set.

Obligatory mention of my experiments with [other ways of thinking about queries](https://github.com/quodlibet/quodlibet/issues/821) here too.

**Comment by pschwede** [comment]
#821 is very similar to this idea. We can move the discussion there, I think.

**Comment by CreamyCookie** [comment]
Closing as #1799 addressed the main issue and #821 and #2803 address usability issues.
