### ISSUE TITLE
tests: Remove dbus-launch usage

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2022]
https://lists.debian.org/debian-devel/2016/08/msg00554.html

**Comment by smcv** [comment]
There's more information for quodlibet's specific situation in <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836054>:

> This Flatpak commit illustrates how eval `dbus-launch` can be replaced
by invoking dbus-daemon directly, avoiding the X11-specific dbus-launch:
<https://github.com/flatpak/flatpak/commit/6cc8062cfb3f9410d54a27e7ccca77c103e441e8>.
It is possible to send both the address and the pid to stdout
("--print-address=1 --print-pid=1") if that would be easier to do from
Python; their order is undocumented but predictable, and I don't intend
to break it in future D-Bus releases.
>
> Alternatively, the test executable could be run through
dbus-run-session(1), which is available since dbus 1.8, the upstream
"old stable" branch available in Debian stable:
>
>     dbus-run-session -- some-test
