### ISSUE TITLE
Waveform Seek Bar: Reports error if played file has 1563 kbps (FLAC)

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2061]
=== SYSTEM INFORMATION:
Quod Libet 3.8 (development, 5f5d448)
Mutagen 1.35.-1
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] linux2
Platform Linux-4.4.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
=== STACK TRACE

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/waveformseekbar.py", line 87, in _on_bus_message
    rms_dB_avg = sum(rms_dB) / len(rms_dB)

ZeroDivisionError: integer division or modulo by zero

----
The played file is a FLAC with 1563 kbps.

**Comment by declension** [comment]
How many channels is the FLAC? Is it just one file?

**Comment by pschwede** [comment]
It happens every time I play FLACs from the same source/album and it's the only one I have where it occurs.

**Comment by declension** [comment]
Thanks. 2 channels is probably over 99.9% of FLACs, but it seems that Gstreamer is not sending any data for that (or all) frames in its pipeline. 

I guess the workaround options are:
1.  Assume an RMS of a constant, e.g. 0
2. or perhaps better, continue the previous value if one is available.
3. Just give up - write a warning to logs and display nothing (or ideally some error state)

**Comment by lazka** [comment]
Looking at the gstreamer code it's not obvious why this could happen. Can you provide the file maybe? (reiter.christoph@gmail.com)

**Comment by pnrao** [comment]
I have this problem too. I noticed that this bug surfaces when I try to play 24-bit FLAC. I don't want to upload original files, because they are quite large. But here is how you can create such a file yourself. You'll have to install the wavefile library (https://github.com/vokimon/python-wavefile), and run the following code:

`
from wavefile import WaveWriter, Format
import numpy as np

with WaveWriter('synth.flac', channels=2, format=Format.FLAC|Format.PCM_24) as w:
    w.metadata.title = "Some Noise"
    w.metadata.artist = "zzzzzzzzz"
    data = np.zeros((2,512), np.float32)
    for x in range(1000) :
        data[0,:] = (x*np.arange(512, dtype=np.float32)%512/512)
        data[1,512-x:] =  1
        data[1,:512-x] = -1
        w.write(data)
`

This synth.flac file consistently crashes waveformseekbar.py. I have attached my synth.flac.

[synth.zip](https://github.com/quodlibet/quodlibet/files/534757/synth.zip)

**Comment by lazka** [comment]
Thanks for the examples

**Comment by pnrao** [comment]
Thank you for fixing the bug so quickly! I have confirmed that this fixes the problem that was occurring with my problem FLACs earlier.
