### ISSUE TITLE
The "random album" plugin thinks it can function in the playlist browser

### ISSUE THREAD

**Issue by draxil** [quodlibet/quodlibet#2072]
The random album plugin thinks it can function in the playlist browser, I assume because the playlist browser reports it can filter by album.

The way this results for me most of the time is it searches the playlist browser for an album that produces no  results and hence the music stops. 

I am not sure what the right fix is here. Probably some other means of telling the random album plugin to determine that it doesn't play well when the playlist browser is up?

I'd be happy to contribute to a fix, but I'm not really sure on the correct path.

**Comment by declension** [comment]
Hmm, yes. The semantics of filtering are a little weird at best in the playlist browser. Yes, it does the right thing (uses the generated query to filter the results of the _current_ playlist), but this is not helpful with the random album plugin.

I'd suggest:
*  the ugly quick fix is indeed to special-case the playlists browser in the Random Album plugin.
* Alternatively rethinking filtering support in playlists browser, though this would be removing features
* The better fix, which I've had in mind since the play order extensions, is to rework this (excellent) plugin to be a shuffle plugin. This would also allow track-level shuffling with the same powerful weighting preferences as this. Possibly needs #894 or similar - i.e. some form of queing / pre-deciding the next tracks a long way (entire album, here) in advance.

**Comment by draxil** [comment]
My pull request contains the "ugly fix". The others sound better with more time and more work :)

**Comment by lazka** [comment]
I guess this can be closed now.
