### ISSUE TITLE
Waveform is recalculated every time a tag is saved

### ISSUE THREAD

**Issue by wifon** [quodlibet/quodlibet#2184]
After upgrading to quodlibet 3.8 I've started to use Waveform Seekbar, which is a great thing to me, but I've noticed some unwanted behaviour. Every time I update metadata in any file, waveform is recalculated for file that is being currently playing. By that I mean, current waveform completely disappears, CPU usage gets to about 45-50% for quodlibet process and then waveform reappears

I think this is unwanted behaviour as obviously no audio data was changed. It may be not big deal with small files, but I've been updating tags in several audio files while playing 1,5 hour podcast - this made quodlibet to eat half CPU's power for quite a long time, as every time I saved tags, waveform got started to recalculate again

my distro: Arch Linux x86_64
quodlibet version: 3.8.0 (package 3.8.0-1)

**Comment by declension** [comment]
Thanks.

This has been at the back of my mind for a while, we should only do it on non-tag changes (other than maybe RG)

**Comment by lazka** [comment]
Caching the waveform for the last 10 songs or so would work as well.

**Comment by wifon** [comment]
Personally, I'd prefer to cache everything - at least that's what foobar2000's waveform plugin used to do back in days I was using Windows

**Comment by lazka** [comment]
Yeah. We currently don't have a good system for caching things on disk. Until then it's at least an easy improvement.

**Comment by declension** [comment]
Also, we need to consider at what "resolution" the data should be in the cache. I did some optimisations around this a bit in #2063. It should be at least the highest pixel width we expect to use (at "high resolution" setting) for maximum quality, but not too high as it can get pretty big for long tracks...

Invalidating the cache is tricky as usual I guess, especially if the file modified time is, but that's only relevant for the disk one (which I favour - a two hour mix can be slooow to render).

Also, a spinner would be good _here_ too whilst we're waiting for the gstreamer response.. :smile:

**Comment by Safari77** [comment]
It recalculates also when I change rating.

**Comment by pschwede** [comment]
Well, caching it for at least one song would be enough for me.

**Comment by ptitjes** [comment]
I experienced that while rebuilding my library (to test for #2291 if "Rebuild library" did take in account removed source directories, which it does not btw).

So, not only does it recomputes the waveform for any change (modified tag or audio in file) of the current song, but it does recompute the waveform of the current song for any change of any song...

That comes down to the `_on_song_changed` handler in `WaveformSeekBar` which does not test whether the currently playing song is in the provided changed songs list.

So this is now fixed in #2289: Waveform is recomputed only if the currently playing song is changed and the display of the waveform is only updated if the audio data has changed.

@lazka I believe that caching previously computed waveforms (based on file modification timestamps) is an orthogonal problem and that an enhancement issue should be open for that alone.
