### ISSUE TITLE
Plugin neither gets listed nor reports an error

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2214]
My plugin [1] isn't listed in the list of plugins. There's also no error report (button beneath the plugin list).

[1] https://github.com/pschwede/quodlibet-plugins/blob/master/order/skip_same_tag.py

**Comment by declension** [comment]
Hmmm, I can't find it in `master` though (should probably live in [`quodlibet/ext/playorder`](https://github.com/quodlibet/quodlibet/tree/master/quodlibet/quodlibet/ext/playorder)). Are you building off your fork?

**Comment by pschwede** [comment]
It's not a fork of QL. It's to be put into `~/.quodlibet/plugins`.

**Comment by lazka** [comment]
I can reproduce, thanks

**Comment by pschwede** [comment]
I investigated a bit. I think my plugin was missing a handler all the sudden. I found out why: It only gets a handler if it inherits from `quodlibet.order.Order`. This was probably new since you introduced the differentiation between *repeat* and *shuffle*.

For me it was tough to see that inheritance from `quodlibet.plugin.plugins.PlayOrderPlugin` is not sufficient anymore. It has to inherit `quodlibet.plugins.playorder.ShufflePlugin` *and* `quodlibet.order.OrderInOrder`.

How about making all classes in quodlibet.plugins.playorder subclasses of `quodlibet.order.Order` resp. `quodlibet.order.OrderInOrder` and `quodlibet.order.OrderRemembered` to make it easier for plugin coders?

At least, the coder must be informed about this change in the docs.

**Comment by declension** [comment]
@pschwede I see, yes. Thanks for investigating the root cause.

There was indeed quite a lot of change when splitting the plugins and separating the concerns; I updated every plugin in the codebase at the time but didn't consider any extra plugins in the wild - sorry!

FYI you don't _have_ to subclass `OrderInOrder` (see `PlaycountEqualizer`) but it's often useful. Bit confusing, I agree. Would be good to make that clearer / simpler, but keen not to change the class hierarchy too much now without careful thought...

Anyway I'll update the documentation to indicate you _must_ subclass either `ShufflePlugin` or `RepeatPlugin` if you want it the plugin to appear in the UI (and thus be usable).

**Comment by declension** [comment]
@pschwede hopefully that's clearer, reopen if you feel it needs more.
