### ISSUE TITLE
travis: use docker

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2222]
so we can test with some newer ubuntu and someday drop 14.04

**Comment by declension** [comment]
It might be useful to Dockerise the build / test outside of Travis too - e.g. quickly testing across multiple distros before pushing (CLI - full graphical ("VM style") may require a bit more thought). I do a lot of Docker at work, so happy to help.

**Comment by lazka** [comment]
Wrote some basic examples first so I can include it in the pygobject documentation: https://github.com/pygobject/pygobject-travis-ci-examples

Not sure if that's the best way to structure things, feedback welcome.

**Comment by declension** [comment]
Looks good. I would have maybe organised with a directory hierarchy (in fact I did this in a patch), but then you have other problems - how to copy the source. But...

We could pre-bake a "builder" image with all the dependencies, into which you _mount_ the source code (this is quite a common pattern when splitting runtime and build-time concerns). If necessary you can override the `ENTRYPOINT` / `CMD` (e.g. exclude some tests). This has the advantages that:

 * It's faster than building a lot (though layer caching is pretty clever usually)
 * the image itself is portable (even: publishable) so that as a dev you don't even have to _build_ any images to test across OSes.
 * If necessary you can affect / produce results on the host filesystem, i.e. it feels more native (or you can mount RO)

It's slightly more complex to invoke, though, and not sure how this would play with Travis.

**Comment by lazka** [comment]
Sounds all good, thanks!

Sadly overriding CMD through run makes docker hang when xvfb is involved, no idea why.
Doing run --detach with exec works on the other hand.

**Comment by lazka** [comment]
Fixed with #2269
