### ISSUE TITLE
Allow editing of tags directly in the songlist(s)

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#2236]
When editing the tags of many files, it is a little cumbersome to edit them in a popup dialog.
It would be interesting the possibility of also edting the tag value directly in the cell of the grid.

**Comment by pschwede** [comment]
The need for easier tagging has been demanded in many issues: #1253 and #1261

I think that I discussed direct tagging in the song list some years ago in the IRC. AFAIR it comes with the cost of a lower performance, because loading an editable grid takes more computation than a non-editable one. But I am not sure anymore.

Today, I asked myself, why this obvious feature is not implemented yet.

**Comment by DavidPerezIngeniero** [comment]
I think the performance of computers nowadays is more than enough.

**Comment by lazka** [comment]
I don't think there would be any performance change.

If we bump our required gtk version we could also use popovers with more complex widgets/feedback:

![asda](https://cloud.githubusercontent.com/assets/991986/22880239/b9b6151e-f1e1-11e6-9053-ed1eff9feb78.png)

**Comment by DavidPerezIngeniero** [comment]
That would be fantastic.  :-)

**Comment by kellogsgit** [comment]
A better tagging is also needed for https://github.com/quodlibet/quodlibet/issues/2243.

**Comment by lazka** [comment]
slightly off topic: I'd prefer if not using musicbrainz is a supported option in call cases, as most people simply don't care. That includes not annoying users of it's missing.

**Comment by kellogsgit** [comment]
Sure, MusicBrainz is only an option for most people. But what do you mean by " I'd prefer if not using musicbrainz is a supported option in call cases," I will look at your developments and try to patch my way, writting my own code, as it is usual in sotware communities.
