### ISSUE TITLE
Add option to confirm removals from playlists

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2248]
I miss an option to turn on a confirmation for removing tracks from playlists, or confirmations for any removals even.

**Comment by zsau** [comment]
Just accidentally clicked "Remove from Library" instead of "Edit Tags" for the second or third time this week, losing some ratings and playcounts (I don't set QL to store that metadata in tags for various reasons).

I'd love to see either this or the undo mentioned in https://github.com/quodlibet/quodlibet/issues/2453#issuecomment-313855099. Is there anything I can help implement?

**Comment by Meriipu** [comment]
I have a half-finished one in a local branch somewhere that I have not had the time to get around to doing cleanly (an earlier pull request https://github.com/quodlibet/quodlibet/pull/2486 for confirmation dialogs were a step towards this)

I think this is abouts where I stopped (I forgot if it worked or not) if you feel like picking it up or looking into a cleaner way of doing it
https://gist.github.com/Meriipu/f59d3a0871b528d58fc9f2ad4e19bec3

maybe it was writing tests for it I stopped at, it has been a while since I looked at it.
