### ISSUE TITLE
Windows install: Unable to use pip-installed modules in QL plugins.

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2285]
Hi,

I recently switched to M$ Windows 10. Trying my favorite player there, I found out that (at least) one of my own plugins doesn't work due to dependencies on undelivered python modules. It's called "opml". I understand that you cannot deliver every package a plugin could possibly require. But is it possible to point quodlibet towards a separate module installation?

Thanks.

**Comment by lazka** [comment]
For opml to work we'd need to ship lxml.

I don't think any prebuild CPython extensions work with our Python since the compilers/ABI are different, but not sure on the details.

**Comment by lazka** [comment]
Regarding the original question, the shipped python.exe in "Quod Libet\bin\" should behave like every other Python installation. You can copy things into site-packages, set PYTHONPATH etc. If you have any ideas on how to improve your use case I'll consider it.

The easiest solution for you might be to port to https://github.com/kurtmckee/listparser and vendor it including its dependencies in your plugin. Since it is Python only, this should also work with our mingw Python.
