### ISSUE TITLE
AUD package (Arch): quodlibet-git does not include python2 futures & feedparser

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2295]
The package does not install all required python modules. Those include:

* futures
* feedparser

However, manually installing the requirements via pip2 works.
I had to install python2-pip in order to do this. Manjaro does not install python2 by default anymore.

**Comment by lazka** [comment]
quodlibet-git isn't controlled by us, but if the current maintainer is no longer interested I can have a look and maybe take over. I don't know how the AUR works..

**Comment by lazka** [comment]
btw, there is the python2-futures and python2-feedparser package in arch, no need for pip.

**Comment by lazka** [comment]
@ochurlaud ping

**Comment by ochurlaud** [comment]
I'm not using the aur version anymore, so I disowned the package. Sorry, I don't have enough time to maintain it currently :S

**Comment by lazka** [comment]
@ochurlaud ok, thanks, no problem.

@pschwede I've pushed an update, untested..

**Comment by pschwede** [comment]
@lazka Do you frequently push updated now?

**Comment by lazka** [comment]
As far as I understand "-git" packages never get updated, you have to rebuild them yourself to get a new version.

**Comment by pschwede** [comment]
That makes totally sense. However I have been missing update notifications about quodlibet. Having done a manual check, `quodlibet` reports a missing Python module: faulthandler. Is there a way to include such things in the AUR?
* dependency updates
* update notifications (e.g. by including the revision number in the package version, etc.)

**Comment by lazka** [comment]
> That makes totally sense. However I have been missing update notifications about quodlibet. Having done a manual check, quodlibet reports a missing Python module: faulthandler. Is there a way to include such things in the AUR?

uh, right, pushed a fix.

Our update check only work for stable releases atm (and it's manual only). It's probably easier for you to just update the package once in a while.

**Comment by ArchangeGabriel** [comment]
@pschwede If you use subscribe to the notifications in the AUR and have activated “Notifications on update” in your preferences, then you should be notified whenever there is an update because of dependencies changes.

If you use an AUR helper, the situation is a bit different, but here it’s @lazka fault: when you change things in the PKGBUILD, make sure the pkgver is set to the latest HEAD, else people having build a more recent version than the one reported wouldn’t see the update through their AUR helper.

@lazka Regarding the PKGBUILD, some little things you should change:

– move $url to https://quodlibet.readthedocs.io/en/latest/, I think this one serves more as a homepage than GitHub, right ?
– remove the .install file and the corresponding line from the PKGBUILD, everything it does is already provided by pacman hooks for more than a year now. ;)
– move pkgver() function before build() one, to be more in line with the order in which they are executed.
– change command in package from `python2 setup.py install --root="${pkgdir}"` to `python2 setup.py install --root="${pkgdir}" --skip-build --optimize=1`, since you’re already building in the build function (`install` implies `build` with setuptools) and `optimize` because we want the `.pyo/.pyc` files to be tracked by pacman.

**Comment by lazka** [comment]
@ArchangeGabriel I've updated pkgrel when I changed things, isn't that enough?

Thanks for the other suggestions. I'll reopen this one for now until that's fixed.

**Comment by ArchangeGabriel** [comment]
@lazka No, pkgrel is almost useless for -git package, because the version check works as following: the `pkgver` part is compared (`r7848.84a0f2e` in the PKGBUILD, but likely `r9077.20ad20d` if you build it), and then if there is a match the `pkgrel` is. But it’s likely someone has a local build that is more recent thant the quodlibet commit number 7848, so that their local version is then > r7848, which means the `pkgrel` is not used at all.

When you update the PKGBUILD of a -git package, you should update the `pkgver` to the latest value provided by the `pkgver()` function (you can obviously run it even without an Arch box, just run the command from it in your git clone of quodlibet). `pkgrel` is only to be used if there were no new commits on the upstream project for a bunch of time, in which case it’s likely people are already sitting on the latest commit and wouldn’t get the update notification.

I hope it’s more clear for you know, but do not hesitate to ask if you still have troubles understanding how things work. ;)

**Comment by lazka** [comment]
Makes sense, thanks!

**Comment by lazka** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=quodlibet-git&id=0e721127a93ab39ea94de72227ec3a696fd02c56

**Comment by ArchangeGabriel** [comment]
@lazka Perfect!
