### ISSUE TITLE
soundcloud.library in song_by_track_id: KeyError: No track with id ...

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2410]
https://sentry.io/share/issue/3134323431352e323833343236313737/

**Comment by declension** [comment]
Hmm. I seem to recall this is one of those "shouldn't ever happen" problems (receiving comments about a song that is not there somehow), but clearly it does in some circumstances. Maybe an async thing, or could even be buggy data coming back. 

Simple answer is just to put it to a `print_w` instead of an Exception I guess..

**Comment by lazka** [comment]
Form what I see could be that the browser/library gets destroyed right at a song change. print_w seems fine.

**Comment by declension** [comment]
Thanks
