### ISSUE TITLE
Importing date added from external sources?

### ISSUE THREAD

**Issue by JCBrouwer** [quodlibet/quodlibet#2461]
Hi, I've just switched over to using Quod Libet and I'm really liking it so far. One thing that I'm currently struggling with is importing old date added information as that's my preferred way of sorting my library.

I've been a bit disorganized for the last 6 months as I've been hopping from music player to music player looking for one that I really like so the metadata that I'm looking to import is a bit scattered. Some of it is in date modified tags on an external hard drive (which I can extract with a simple bash script I wrote) and some of it is in an old iTunes library.

I've looked at the options that Quod Libet gives to interact with its library and I'm thinking I can either use Custom Commands or try to do it via a Python script / console. Thing is I haven't really been able to figure out how to do it by looking through the documentation. Is there a section that deals with these kind of bulk changes based on fuzzy searches in the QL database? Or I guess more generally, what is my best option for doing this?

Also, do I need to add a custom tag to store this information, or can the Date Added tag be modified on its own? If I do need to add a custom tag, how do I do this? The FAQ refers to the Editing Tags page in the documentation, but that page doesn't cover how to make a custom tag at all.

Thanks!

**Comment by declension** [comment]
> Is there a section that deals with these kind of bulk changes based on fuzzy searches in the QL database? 

No, sorry


> Or I guess more generally, what is my best option for doing this?

Probably a songsmenu plugin, if you're comfortable writing Python. If not, as you say, the Custom Commands plugin lets you externalise a lot of these types of problems, at the cost of full API access of course.  

> Also, do I need to add a custom tag to store this information, or can the Date Added tag be modified on its own?

If you're writing a plugin, or in the QL Python console you _can_ modify the Date Added: e.g. in the console you can do  
````python
sdict[0]['~#added'] = 1234567890    # or maybe time.mktime((2017, 06, 30....) 
````  

>  If I do need to add a custom tag, how do I do this? 

A custom tag is really just _any_ tag that's not well known (though this depends on the underlying format). You can add any tag from the Edit Tags window by inventing a name for it.

HTH

**Comment by minombreespollo** [comment]
Hey everyone.

Soo.. I'm new to Quodlibet, Linux, python and basically everything related to solving this issue. I've had a hard time understanding all the tags thing that makes the QL so powerful and modifying them seems above my current understanding. 

I would like to change the "added" tag as well so that I can sort my library and get some useful playlists. How can get acquainted with the concepts necessary to do this? even if I have to change it album by album or song by song I wouldn't mind, I'd take the opportunity to revisit each and every song I love.

My main issue is that I don't know which file to modify or how to access the modification tool. I think that would be a great start.

Thank you for any help provided.

**Comment by JCBrouwer** [comment]
@minombreespollo If you're willing to go a song at a time then you can use the Python Console as suggested above. First enable it File > Plugins then check the box next to Python Console. Select your entire library and then right click Plugins > Python Console. Now you can change each added value of your songs individually. Using the console is a bit clunky though.

I've been trying to write a Python script that can import the added tags in bulk but I've been running into an issue trying to access my QL library. The following line gives me an ImportError: No module named quodlibet.formats.mp3

`with open(os.path.expanduser('~/.quodlibet/songs'), 'rb') as f:
    qll = pickle.load(f)`

So I've been trying to install quodlibet as a python package to my standard library by running

`python ./setup.py install`

In a cloned quodlibet repo, but it's failing to build properly

> running install
running build
running build_py
running build_scripts
copying and adjusting quodlibet.py -> build/scripts-2.7
copying and adjusting exfalso.py -> build/scripts-2.7
copying and adjusting operon.py -> build/scripts-2.7
changing mode of build/scripts-2.7/quodlibet.py from 644 to 755
changing mode of build/scripts-2.7/exfalso.py from 644 to 755
changing mode of build/scripts-2.7/operon.py from 644 to 755
moving build/scripts-2.7/quodlibet.py -> build/scripts-2.7/quodlibet
moving build/scripts-2.7/exfalso.py -> build/scripts-2.7/exfalso
moving build/scripts-2.7/operon.py -> build/scripts-2.7/operon
running build_mo
Error: 'gettext' not found.

Gettext is installed via homebrew, however. Any advice @declension, is there a better way to access my library via a python script?

**Comment by minombreespollo** [comment]
@JCBrouwer Thank you very much for your help. I'm 30 albums into it and I am loving Quodlibet! I have noticed that my past player (OSX swinsian) stored epoch times without the first digit and sometimes the dates are set to the future which is very strange. With a script I wouldn't have noticed that. I still have 12500 songs to go so I completely understand why you would not do all your library.

Hope you get your answer by @declension or sombody else. What other outlets for this kind of issues are there? is there a subredit or a group or something?

**Comment by declension** [comment]
@JCBrouwer I don't run OS X myself so there's only limited help I can give here. Most of the setup should be covered by the [OS X bundle scripts](https://github.com/quodlibet/quodlibet/tree/master/osx_bundle) though, so you could try that.

Generally, if you want the programming environment of QL available, it will be _much_ easier to do this from _within_ a working QL environment (once that gets solved) rather than hacking the pickle file directly. As per my first reply this is either a songsmenu plugin or using the Python Console (easier but less power).

Within the plugin you are free to import libraries e.g. `lxml` (though you may want to try the standard `etree` first if performance isn't an issue, as that's used in various places around the codebase) and you'll have easy access to song wrapper objects for reading and writing once the plugin fires. There are lots of songsmenu plugins to look at, the Duplicates Browser is one that is often used to update entire libraries based on searches, so could be helpful (though it's a bit complex / UI-heavy in places). Also the _Import Metadata_ plugin maybe.

**Comment by CreamyCookie** [comment]
Closing this for now. If you want a plugin to import data from specific formats / sources, please create a new issue.

**Comment by snezhniylis** [comment]
If you're up to writing your own soluition, here's a starting snippet I came up with after some research:

```py
import os
import quodlibet
library_path = os.path.join(quodlibet.get_user_dir(), "songs")
library = quodlibet.library.init(library_path)
library.get_filename("/home/user/path to file.mp3")['~#added'] = 123456789 # unix timestamp, or, as mentioned above, time.mktime((2017, 06, 30....) 
library.save()
```
You can execute this piece of code using Python Console plugin.

Alternatively, if your collection is not so big, [Import / Export plugin](https://github.com/quodlibet/quodlibet/pull/3705) can export your tracks' [internal tags](https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html) in json format, so you can manually edit them, and import back afterwards.
