### ISSUE TITLE
"Jump to Playing Song" no longer works in filebrowser

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2629]
It is working in search browser.

**Comment by Meriipu** [comment]
Automatically jumping to the playing song once the track changes, or the CTRL+J shortcut?
If automatically, is it enabled in File>Preferences under the Song List tab (tick "Jump to playing song automatically")?

What part of it no longer works? 

in the file system browser with some directory selected:

I am on commit 5b1152ce3151cf950aba063f91f6a75d551ae3d7 right now, and with the option enabled once a track finishes, it scrolls the list to the track in question. If another track is marked/selected (e.g it has that blue highlight, but is not playing), it remains selected even after the automatic jump.

If I scroll the currently playing track of of view and press CTRL+J, it also jumps to (and actually selects) the playing track.
The only issue I have is that pressing CTRL+J with another track selected occasionally only clears the other selection and does not scroll until CTRL+J is pressed a second time.

**Comment by spxxxk** [comment]
Sorry about the missing info .. 

I'm talking about the menu entry "Jump to Playing Song" / "ctrl-J" shortcut.
What used to work : 
- play folder1/track1.mp3
- go to folder2 (any that isn't folder1)
- press "ctrl-j"
-> Filebrowser shows folder1 and select track1.mp3

Now it does nothing, ie not go to folder1

Jumping to playing track from the same folder does work.

**Comment by Meriipu** [comment]
Do you know of which/some earlier specific commit/version that worked in

**Comment by spxxxk** [comment]
No idea. 
All I know is that it was working 2-6 months ago on Ubuntu 16.04, with QL unstable PPA version.
Now, it doesn't on Xubuntu 16.06, and QL version : 3.9.99+9475~1b6539c53-0~ppa0~xenial.

Don't know if it's a QL update, the OS switch or the pc switch..
I can't test on older pc since it died.

**Comment by Meriipu** [comment]
So the expected behaviour in the filesystem browser is that the directory that the current track is in gets selected when CTRL+J is pressed so that the current track is visible in the list again? 

I can not get it to work in the search browser as mentioned in the original post though (make a track play, search for something else so the current track is not in the list to simulate the selecting of a different directory from the filesystem browser, then press CTRL+J) - nothing happens in the searchbrowser if the track is not in the list for me when I press CTRL+J either. 

Although I suppose it might be awkward in the search browser for CTRL+J or the automatic jumping to cancel your current search and bring back the previous search somehow, maybe. 

I tried it in the playlist browser, and it actually selects the (next, first occuring?) playlist the track is in and then jumps to the track when CTRL+J is pressed, so from that would have expect the same to happen in the filesystem browser (which does not happen which this bug is about).

**Comment by spxxxk** [comment]
> So the expected behaviour in the filesystem browser is that the directory that the current track is in gets selected when CTRL+J is pressed so that the current track is visible in the list again?

Exactly. Sorry I failed to say that before... 

> I can not get it to work in the search browser as mentioned in the original post though (make a track play, search for something else so the current track is not in the list to simulate the selecting of a different directory from the filesystem browser, then press CTRL+J) - nothing happens in the searchbrowser if the track is not in the list for me when I press CTRL+J either. Although I suppose it might be awkward in the search browser for CTRL+J or the automatic jumping to cancel your current search and bring back the previous search somehow, maybe.

Me neither.
Not sure why I mentionned the searchbar in first post since, in filebrowser, when in folder with current track, it does work.

Could have been a bug all along but it was really usefull since QL remembers the current track but not the last folder in filebrowser accross restarts.

**Comment by Meriipu** [comment]
works for me now

**Comment by lazka** [comment]
@spxxxk thanks for the report
