### ISSUE TITLE
Duplicate results while searching people

### ISSUE THREAD

**Issue by Treferwynd** [quodlibet/quodlibet#2639]
When I search for someone I get duplicate results in the column which is `<~year|[b][i]<~year>[/i][/b]> <~dirname> - <~people> - <album>` (I included dirname to show that they are actually duplicate entries)
![2017-11-28-15 01 57-screenshot](https://user-images.githubusercontent.com/2520587/33323558-247b7bc0-d44d-11e7-8dc3-da3d30d9c6d8.png)

* What did you expect to happen?
 Not to see duplicate entries, e.g. you can see that the tag `~people` is shown one time as `Mozart` and another time as `Gulda; WPO, Abbado`, what I expected was to see only one entry with `Mozart, Gulda; WPO, Abbado`, as shown in the lower half.

QL Version 3.9.1, on Arch Linux, Python 3.6.3

Edit: note this also happens while searching without the `~people` tag:
![2017-11-28-15 08 15-screenshot](https://user-images.githubusercontent.com/2520587/33323887-278dfd0a-d44e-11e7-8c03-864dfabb064b.png)

**Comment by Treferwynd** [comment]
Is this the intended behavior?

**Comment by urielz** [comment]
Hi @Treferwynd: 

 I can reproduce this on my end. I think the culprit is the ~people tag in _<~year|[b][i]<~year>[/i][/b]> <~dirname> - <~people> - <album>_ . 

The problem arises because the ~people tag combines multiple tags in one (from user's guide: albumartist, artist, author, composer, ~performers, originalartist, lyricist, arranger and conductor). This means that if any of those tags contains whatever you're searching it will show up as a hit. 

Whether this is the intended behavior I don't know, @lazka  or @declension would probably know the answer. Personally I'm with you, I'd rather see a unique results regardless of how many positive hits the ~people tag has...

**Comment by Treferwynd** [comment]
Hi, yep I agree, the ~people tag is definitely the culprit. I wanted to ask if this was the intended behavior before trying to fix it (and admittedly to bump the issue)

**Comment by declension** [comment]
It's hard to say exactly without knowing what your individual tags are set to @Treferwynd. Perhaps you can list `artist, `composer`, `performer` etc for the above examples.

From the semicolons there I'm wondering if all these tags are split fully (ie to multiple values). If not, you will definitely get messy results when using aggregate tags like `~people` (ie expected behaviour)

**Comment by Treferwynd** [comment]
Sure:
* artist: Mozart
* composer: Mozart
* performer: Gulda; WPO, Abbado
![2017-12-23-08 56 39-screenshot](https://user-images.githubusercontent.com/2520587/34318193-bc56a532-e7c1-11e7-9c17-b4e6b05f9181.png)

In the preferences I've set `Split on: / & ,`, now I added the semicolon, and I encountered a bug where changes to `Split on` are reset when I restart QL (I'll do a better report after the festivities).

So I added splitting on semicolons and even changed the semicolons to commas but nothing changes:
![2017-12-23-09 34 58-screenshot](https://user-images.githubusercontent.com/2520587/34318298-cd83b41e-e7c4-11e7-82a4-294db9791b50.png)

**Comment by declension** [comment]
Ah, right. 
This is a common misunderstanding with QL actually - **no dynamic tag splitting is done in queries**. If you want to split tags, this can be done _permanently_ using the _Split into Multiple Values_ context menu item in the Edit Tags window (and _this_ is what the configuration is about).

We should probably make the behaviour clearer - there are quite a few issues that come up around - see especially #2407. Perhaps if the long-overdue configuration improvement #1029 itself were done it would serve as documentation of sorts, or at least reduce the misunderstanding when users look at the preferences.

**Comment by Treferwynd** [comment]
Ok, I've split the tags:
![2017-12-27-11 45 24-screenshot](https://user-images.githubusercontent.com/2520587/34379474-b2076dae-eafb-11e7-8580-706e11f7ff8b.png)

But the result is actually worse, now I get the same album four times:
![2017-12-27-11 44 33-screenshot](https://user-images.githubusercontent.com/2520587/34379482-bea2f920-eafb-11e7-8529-e9001158a02c.png)

P.S.: I think the split thing just needs to be done automatically, because doing it by hand is not feasible and there wouldn't be any more misunderstandings

**Comment by declension** [comment]
> But the result is actually worse, now I get the same album four times:
Yes, I see. Technically though, that's not an album but a _value_ for `<~year> - <~people> - <album>`. Multiple values for this expression are treated as separate entries in the paned browser, to allow exploring of multi-valued tags (and expressions in fact).

If you want the album uniquely in that pane, then `<album>` alone will do (and using `~year` in this case I imagine, but I'm guessing you wanted the _display_ of `~people` too).  But fundamentally, if you're browsing people, and there are lots of people involved, then there will be lots of rows generated - I don't see a way around this.

Things that might prove more useful for your use-case here: 
* Using `conductor` / `artist` / `composer` as these are usually single-valued
* ...or moving `~people` to a third pane, so that you can easily select _All_ to group together the album

> P.S.: I think the split thing just needs to be done automatically, because doing it by hand is not feasible and there wouldn't be any more misunderstandings

Yes, see discussion on a plugin for this in #2407

**Comment by Treferwynd** [comment]
First of all, thank you for your patience...
I'm trying to achieve is something like this:
![2017-12-27-16 17 18-screenshot](https://user-images.githubusercontent.com/2520587/34385235-91a112d8-eb21-11e7-9258-558d12e5cae8.png)

As you can see I have all the relevant info at a glance. As the songs with same `album` are lumped together I think it'd make sense to merge those with the same `~people` as well

**Comment by declension** [comment]
> First of all, thank you for your patience...

No worries :)

> As you can see I have all the relevant info at a glance

Yes, I'm just not sure this will be possible in QL. Personally I'd approximate with panes:
1.  `~composer` 
2. `album` (or better, perhaps `grouping` if you use that) 
3. `people` (or `artist` / `performer` / `conductor` perhaps)

As mentioned above having these as panes gives you the power to aggregate or not (_All_, _Unknown_ etc), and the default is not to separate these.

Note also you can also use tag _expressions_ to allow defaulting e.g. `<composer|<composer>|<artist>>` or even `<grouping|<grouping>|<album|<album|<title>>>` which is quite useful for less organised libraries.

**Comment by Treferwynd** [comment]
> > As you can see I have all the relevant info at a glance

> Yes, I'm just not sure this will be possible in QL.

I'll try to tinker with the code and see if it's possible.

If that doesn't work, I think `grouping` is the right idea: since my library is _pretty well organized_ (yep, I took that personally :P) I should be able create the tag programmatically.

Thanks for your time declension!
If @urielz has no objection, I'm closing this issue.

**Comment by lazka** [comment]
We also have a separate display(non-grouping) pattern separated by ":", but due to gtk+ bugs this cuts of the text in many cases.

``<~year|[b][i]<~year>[/i][/b]> - <album>:<~people>``

**Comment by Treferwynd** [comment]
Uhm, interesting, I'm playing with it now, but what does non-grouping means? It actually groups all the `~people` together.

**Comment by lazka** [comment]
The left pattern generates a set of keys which is used to group the songs. By non-grouping I meant it doesn't affect which songs end up where, it just gets applied on the songs represented by that row.

**Comment by Treferwynd** [comment]
Ok, I've found another way: using `<composer> · <performer>` instead of `<~people>` groups the results as expected (if I don't split the `performer` tag).
So I still think this is a bug, IMHO a combined tag should work like the combination of the tags it combines (if that make sense...), look at the difference:
* second column: `<~year> - <~people> - <album>`
* third column: `<~year> - <composer> · <performer> - <album>`
![2018-01-09-11 54 48-screenshot](https://user-images.githubusercontent.com/2520587/34717683-2f61c1c2-f534-11e7-971a-a7915cb17d4b.png)

Since I've found a work around, if this is the intended behavior I'll close the issue.

**Comment by Treferwynd** [comment]
To further the point that combined tags (like `~people` and `~performers`) should work like the combination of the tags they combine, if I split the `performer` tag I get duplicate results in the 3rd column like in the 2nd one, and changing `<~year> - <composer> · <performer> - <album>` to `<~year> - <composer> · <~performers> - <album>` doesn't actually make a difference.

**Comment by Treferwynd** [comment]
I'm closing the issue, evidently I misunderstood how combined tags work, and the solution in [my previous comment](https://github.com/quodlibet/quodlibet/issues/2639#issuecomment-356254773) is satisfying. Thanks for your time!
