### ISSUE TITLE
URL from "Check for Updates" and "Online Help" do not "match"

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2753]
If the URL from the "Check for Updates" dialog is opened it points to a "Downloads" page of the revision `f6a52946`.
If The URL from "Online Help" is opened and the user changes from "User Guide" to "Downloads", than this page has the revision `dc9cbf59`. Searching for most current downloads fails, since 3.9.x is the "youngest" listed version.
Is the revision of the "User Guide" quodLibet points to the "youngest"?

**Comment by lazka** [comment]
The online help points to the documentation version of that release (there is also a note on top of each page pointing out that it's an older version). But maybe we should just point the newest..

**Comment by MartinL0815** [comment]
Ok - than in other words.

If I use a version of quodLibet, than it is okay to get to the related "User Guide".
Yes, this "User Guide" page tells to be not the most current, so I can always change to the most current "User Guide".
But if I click in the "User Guide" on Download, I'd expect to get to the current downloads list.
Okay, even this page does tell about being not the most current.
But, if the most current version 4.0.2 opens an "User Guide" pointing to a "Downloads" page not providing 4.0 downloads, than something is wrong, isn't it?

And eventually my high-contrast-mode is responsible for not really notizing this "hint" (Internet Explorer 11):

> 
![outdated note in high-contrast-mode](https://user-images.githubusercontent.com/525700/35626206-42247aa8-0695-11e8-9d83-2e46c2ff4c75.png)

This way it looks in Chrome without any high-contrast-changes:

> 
![outdated note in Chrome](https://user-images.githubusercontent.com/525700/35626250-668c3ce6-0695-11e8-9fdc-93470deee65d.png)

What's about enhancing the "Notes" by adding a border or less subtle font size differences?

So, there is no real problem, only my problem of recognizing important information needed to validate the value of information and to react on this.

**Comment by lazka** [comment]
Yeah, I agree.

The only thing i can think of to get both the newest downloads and older guide is to split the website in two separate websites. But I quite like how things are in one place atm.

When we added the versioned user guides (mainly because readthedocs just happened to support branch builds..) the thinking was that we could change things in the docs without having to think about older versions.

But in reality things don't change that much and the split is, as you said, confusing.

I'm going to just point everything to the newest version.
