### ISSUE TITLE
Reverse DNS App ID

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2792]
For flatpak we need to unify our dbus name/desktop id/appdata id.

We currently only have "net.sacredchao.QuodLibet" for dbus. We could either just use that or go with "io.github.quodlibet.QuodLibet" and "io.github.quodlibet.ExFalso" maybe.

Open questions: Is there anything we can do to improve the transition (re gnome software appdata etc)

**Comment by declension** [comment]
+1 to `io.github.quodlibet.QuodLibet` etc

**Comment by lazka** [comment]
on IRC, re transition:

```
<brtln> you can use <provides> <id>old_id</id></provides> in your appstream file
```

**Comment by fkrull** [comment]
Another point: for any Flatpak that exports multiple desktop files, all the desktop files must have the app ID as prefix (see https://github.com/flatpak/flatpak/issues/750). If Ex Falso should be included in the same Flatpak as QL, its app id would have to be something like "io.github.quodlibet.QuodLibet.ExFalso" so that it's prefixed with the QL app id.

(Something I just thought of: it might be possible to set the Flatpak app id to "io.github.quodlibet" with desktop files "io.gh.ql.QuodLibet" and "io.gh.ql.ExFalso". But I don't know if that's allowed or even a good idea.)

**Comment by lazka** [comment]
@fkrull thanks for the info. I slightly tend towards separate flatpaks for QL/EF, so we get multiple entries/screenshots in gnome software/app stores etc. Any thoughts?

**Comment by fkrull** [comment]
@lazka The one issue with that is that the applications would not share a config directory since they'd be in different Flatpaks, so if someone set up their tag editing plugins in QL, they wouldn't show up in EF. I don't terribly mind that personally but it's something to keep in mind.

Separate packages should hopefully solve the app identity issue I was having with EF over in #1806, though.

**Comment by lazka** [comment]
Uh, ok. I don't mind either really. Maybe we can just start with QL only and handle EF later.

**Comment by lazka** [comment]
> How important is backwards compatibility for the D-Bus names?

If you mean net.sacredchao.QuodLibet, I don't mind if that goes away with flatpak.

**Comment by lazka** [comment]
I've updates the PPAs for the file renames, if anyone sees anything funky please report.

Thanks @fkrull
