### ISSUE TITLE
No icon in Ubuntu dock with Wayland on 18.10

### ISSUE THREAD

**Issue by Valeryan24** [quodlibet/quodlibet#2889]
Hi, I made today a fresh installation of Ubuntu development version 18.10, launched Wayland session, then installed Quod Libet from the default Ubuntu package.

When I run QL, it works fine, just there are no correct icon on the dock nor on the top bar, but this (bottom of the screenshot):

https://framapic.org/U5PfilFgyGtS/0eNA4cqulf1Y.png

Then I updated with the unstable ppa, it gives the same result for dock and top bar icon.

When focus is on another program and I click on the button, it well switches back to QL, but icon is not movable on the dock and can not be added as favorite (bookmark).

Thanks !

**Comment by lazka** [comment]
Thanks!

**Comment by hdbhdb** [comment]
I can confirm the same issue in Ubuntu 17.10 with Wayland. 

I can favorite Quod Libet from the the applications menu and it appears on the dock, but when I click the Quod Libet icon on the dock, it launches a window under a new icon (the same null icon that Valeryan24 has indicated).

**Comment by fabsmusicjunkie** [comment]
i'm having the same issue on arch

**Comment by frestr** [comment]
I think this is because of an incorrect WM_CLASS string in the desktop file.

Can any of you test whether replacing the line

`StartupWMClass=Quodlibet`

with 

`StartupWMClass=quodlibet`

(i.e. with a lowercase q) in your system's installed desktop file fixes the problem?

(The location is `/usr/share/applications/io.github.quodlibet.QuodLibet.desktop` for Ubuntu.)

**Comment by hdbhdb** [comment]
yes, this fixed the issue!

**Comment by lazka** [comment]
thanks!
