### ISSUE TITLE
No details on changing keybinds

### ISSUE THREAD

**Issue by someguyss** [quodlibet/quodlibet#2919]
Hello

In the FAQ it states to solve the issue with spacebar on certain keyboards to 'use the method above' to change keybinds but there is no explanation above, only details about the config file (which I assume you use). How exactly do you go about changing keybinds? I'd like to edit more than just that bind.

I've just moved from Windows and after spending hours trying to get MusicBee to work acceptably with Wine gave up, Quod Libet is so far all but perfect with this issue specifically standing out for me along with the lack of a stop button in the GUI (only a pause button), which frankly isn't a huge problem.

Whatever the solution is it should probably be added to the documentation unless it's somewhere I haven't found it.

**Comment by frestr** [comment]
> 'use the method above'

It references a question that was later removed because the solution became obsolete. The doc should be updated to reflect that.

>  to change keybinds but there is no explanation above

The doc explains how to fix that particular issue with the spacebar, which has to do with the keymap (what keys are sent to applications when a physical key is pressed). It isn't really related to custom keybindings in QL.

The keybindings in QL is AFAIK hardcoded and can't really be changed. It might be possible to change them by hacking with GTK3, but I'm not familiar with that.

If you want to use another key for pause, you would normally map that key to the XF86AudioPause key in your OS.

**Comment by lazka** [comment]
In the configuration folder there is an "accels" file where you can uncomment lines and change some keybindings. It only covers parts of the main menu, is not that easy to use, and there is no guarantee that it will continue working in the future, which is why it isn't advertised in the docs.

re stop, you can call `quodlibet --stop`

**Comment by someguyss** [comment]
Ok, that all makes sense. 
>re stop, you can call quodlibet --stop
Perhaps the documentation could include basic instructions on how to do this? I've worked it out from a quick search but not all users will be comfortable doing that.

Would you like me to close this issue?

**Comment by frestr** [comment]
> Would you like me to close this issue?

Yeah, I think we can close it.
