### ISSUE TITLE
Question about ~playlists tag

### ISSUE THREAD

**Issue by Andy3142** [quodlibet/quodlibet#2942]
I'm a beginner with QL. ReadTheDocs says the ~playlists tag "is populated with a list of all the playlists that song appears in."

 A question: Is there syntax in the Search bar to search for the playlists which a specific song appears in? 

I don't need this any longer, because I added ~playlists to the displayed columns and so got the information in a different way, but I just spent a couple of hours failing to find such a syntax so would like to know (or, if there is definitely no such syntax.)

Many thanks

Andrew

**Comment by declension** [comment]
Sure, though it's not really special syntax:

`~playlists="Metal Madness"` or whatever

**Comment by Andy3142** [comment]
@declension, no, what this does is to list all the songs in any playlist whose name includes "Metal Madness". It doesn't list all the playlists in which the song "Metal Madness" occurs.

**Comment by declension** [comment]
I see. 
The problem here is all the browsers' main panes are _songlists_, i.e. song-based list views (effectively at least).

> It doesn't list all the playlists in which the song "Metal Madness" occurs.

If you want to select _playlists_, the playlist browser _would_ be the one to use, but its search is tied to its songlist not its actual unique browser (of playlists, on the left). So searches are about the songs within.

I've considered adding playlist searches a few times, but as no browser has two searches, it'd be very unintuitive (and the search-within-playlist is still a primary feature). If it did have this, you could potentially select a playlist on its contents, as all collections (notably including albums in the various album browsers) are aggregated pseudo-songs when presented to the matcher, with tags typically aggregated in "the right way" across their contents - e.g.
 * string tags are turned to lists (searchable)
 * `~#length` is summed
 * `~bitrate` is averaged.
...with a few collection only tags introduced, e.g. `#tracks`.

So a `~title` or `~filename` search _would_ probably do the right thing

**Comment by Andy3142** [comment]
Dear @declension,
Thanks for explaining that. It is a relief to know I wasn't being stupid. I tried everything. I feared it was  like the scene in Lord of the Rings where Gandalf spends hours failing to open the door that says "Speak Friend and enter."

May I say that QL is a VERY good music player. I need a library manager that works on Windows and Linux and will cope with a complex library. I must have tried everything you can download and this is far and away the best.

**Comment by CreamyCookie** [comment]
Great to hear, and I agree. For me, it's the best music player I know. (btw. Please close this issue if your questions have been answered.)
