### ISSUE TITLE
Queries affect whole albums instead of tracks

### ISSUE THREAD

**Issue by LdBarthel** [quodlibet/quodlibet#3091]
Quodlibet 4.2.0 on Arch Linux

I have some saved queries that I use for a jukebox mode, the most important of which are queries that select for or exclude Christmas and commentary/dialogue tracks.
[queries.saved.txt](https://github.com/quodlibet/quodlibet/files/2708773/queries.saved.txt)

Several Ian Anderson "solo" albums include Christmas tracks. However, my saved queries now select the entire album when choosing Christmas music. Albums which have a single Christmas track are completely excluded from unseasonable queries.

For that matter, searching on ratings is now erratic: a search for ratings < .50 yields results that include .80 and 1.00 tracks, while reversing the search to > .50 completely excludes the highly rated tracks, apparently because some tracks are rated <.50.

I've double checked the active plugins and believe I have all the requisites active.

**Comment by declension** [comment]
Thanks for the report. It's difficult (IMO) to understand (and therefore reproduce) the problem here though. Do you think you could reformat this to be:
1. Steps to reproduce the problem, ideally with example / made-up track metadata (e.g. `song-a.mp3` with rating 0.1, _Song B_ by _Artist C_ with rating 0.8, etc) 
2. What you expected to see
3. What you actually saw

Also, if this functionality has changed (i.e. was working on an earlier version), please post which was the last version you _know_  worked as expected (i.e. as described in (2)).

**Comment by davidSchlosser** [comment]
Similar to the issue I raised in #2484

**Comment by LdBarthel** [comment]
Sample album data using 5-star rating (0.2, 0.4, 0.6, 0.8, 1.0)

Track, Artist, Album, Title, Genre, Rating
1 Artist_1, Album_1, Track_1-1, Rock, 0.6
2 Artist_1, Album_1, Track_1-2, Rock, 0.4
3 Artist_1, Album_1, Track_1-3, Christmas, 0.8
4 Artist_1, Album_1, Track_1-4, Rock, 1.0
1 Artist_1, Album_2, Track_2-1, Rock, 0.2
2 Artist_1, Album_2, Track_2-2, Rock, 0.6
3 Artist_1, Album_2, Track_2-3, Rock, unrated
4 Artist_1, Album_2, Track_2-4, Rock, 0.0
1 Artist_2, Album_3, Track_3-1, Christmas, 0.6
2 Artist_2, Album_3, Track_3-2, Christmas, 0.2
3 Artist_2, Album_3, Track_3-3, Christmas, unrated
4 Artist_2, Album_3, Track_3-4, Christmas, 1.0

Results for sample queries:
1) Rating > 0.5
Expected: Tracks 1-1, 1-3, 1-4, 2-2, 2-3, 3-1, 3-3, 3-4 (unrated tracks default to 0.6)
Get: No tracks

2) Rating < 0.5
Expected: Tracks 1-2, 2-1, 2-4, 3-2
Get: All tracks

3) Genre = Christmas
Expected: Tracks 1-3, 3-1, 3-2, 3-3, 3-4
Get: Tracks 1-1, 1-2, 1-3, 1-4, 3-1, 3-2, 3-3, 3-4

4) Genre != Christmas
Expected: Tracks 1-1, 1-2, 1-4, 2-1, 2-2, 2-3, 2-4
Get: Tracks 2-1, 2-2, 2-3, 2-4

Unfortunately, I cannot pinpoint when this behavior changed. After I got the saved queries working correctly, I didn't use them frequently. For most of the year I listen to whole albums.

HOWEVER, based on davidScholosser's comment while I was preparing this, I went back and experimented with changing views.

It now appears that if I'm in the "Search Results" browser, the searches work as expected. But if I start in any other mode and select a saved search, I get unpredictable results. (For example, starting in "Cover List", I got many correctly matching tracks, but only 5 of the album covers were shown.)

So, for my current use case, this is solved: I simply have to remember to NOT use the other browser modes. But from a usability perspective, we may want to provide a more consistent experience for the end user when searching from within each browsing mode.

**Comment by CreamyCookie** [comment]
> a search for ratings < .50 yields results that include .80 and 1.00 tracks, while reversing the search to > .50 completely excludes the highly rated tracks,

I think that works as intended.  When you're in an album browser, the rating tag uses an average of the ratings of the tracks in the currently selected album. 

You can use [numeric functions](https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#id2) to use the smallest value. (`~#rating:min`)

> Albums which have a single Christmas track are completely excluded from unseasonable queries.

Unless I'm missing something, that's also correct. If the query starts with something like `&(genre!=christmas, ` then no album should be returned that contains a christmas song.

Maybe you want a way to query something like "return albums where most tracks aren't christmas ones"?

 (pseudo syntax: `percentage(genre!=christmas) > 0.9`)

**Comment by bassstorm** [comment]
> Maybe you want a way to query something like "return albums where most (e.g. 90%) tracks aren't christmas ones"?
> 
> (pseudo syntax: `percentage(genre!=christmas) > 90` )

By the way - yes, I was thinking about something like that.
Use case: often I like to play an 'ambient' album to chill, so a query to choose a highly rated album where most of the tracks tagged with 'ambient' genre would be a great deal of usability.

**Comment by declension** [comment]
>    percentage(genre!=christmas) > 90 )

Interesting. Related: we could just have another aggregation (across collections), but for text tags. e.g.

`#(originalartist:prevalence > 0.75)`

To find (mostly) covers albums

This would mean quite a big change, in that any arbitrary tag could become a numeric tag with one of those new qualifiers, but feels very feasible (`prevalence` is the best name I could come up with for the example one now)

To get the syntax allowing derived variables in tags' _values_ that  @CreamyCookie mentioned: perhaps a query plugin is best (else... big parser changes)

**Comment by CreamyCookie** [comment]
@declension 

> To get the syntax allowing derived variables in tags' values that @CreamyCookie mentioned: perhaps a query plugin is best (else... big parser changes)

Some ideas if we were to do this (via plugins or not):

**name**|**description**|**example (in album browser)**
:-----|:-----|:-----
`count`|Return number of entries who fulfill condition|`count(~length > 0:01:00) - number of songs longer than a minute`
`percentage`|Return number of entries who fulfill condition divided by number of songs in album|`percentage(@(missing: ~#rating) > 50)` - more than 50% of the songs are not rated
`weighted_percentage` (a bit long)|multiply each value (true = 1, false = 0) by the duration, then sum it and return the sum divided by the total duration of the album|`weighted_percentage` with the genre check would probably be better, since small christmas songs shouldn't get the same weight as a long christmas song. After all, you want to know what part of the album is christmas stuff.
`any`|Shortcut for `percentage(...) > 0`|`any(~#rating > 0.7)` - all albums who contain great songs (even if most songs in the album suck)
`all`|Shortcut for `percentage(...) == 1`

> This would mean quite a big change, in that any arbitrary tag could become a numeric tag with one of those new qualifiers, but feels very feasible (prevalence is the best name I could come up with for the example one now)

I don't think that would solve the genre use case above (finding albums with mostly Christmas songs), but that idea sounds great! 

Not only would it allow for `all` (prevalence == 1) and `any` (p > 0). It could in theory also completely replace `@(missing: INSERT_TAG)` which while nice, does currently have some issues: #3046 (`@(missing: ~#lastplayed)` does not work for albums) and is a bit annoying to type.  

So in a song browser you'd just use `#(lastplayed:prevalence > 0)` to search for songs who have a `lastplayed` date, and the good thing is the same would work in album browsers. (And `#(lastplayed:prevalence = 0)` for finding songs or albums who have not been played.)

**Comment by declension** [comment]
@CreamyCookie these are some really good ideas, and - slightly related - I think if doing #821 nowadays, a Python-like syntax might make more sense than ever, with `in`, `all` / `any`, `len` (over / as well as `count` perhaps) etc...

**Comment by CreamyCookie** [comment]
I've extracted the album function ideas (`percentage(genre = christmas) > 50`) to its own report:  #3429
