### ISSUE TITLE
Copy Music to Music folder when adding new music

### ISSUE THREAD

**Issue by kellertobias** [quodlibet/quodlibet#3186]
I've used banshee for the last years and now (in ubuntu 19.04) banshee cannot be installed anymore. Sadly all my python-scripts for music management are obsolete now and so i am searching for a new music player. QuodLibet saved my ass by being able to load and change the Metadata on the files directly and it looks as if it would only miss one feature (or I haven't found it yet): Importing Music and creating the folder structure for new songs.

**Comment by declension** [comment]
Hi.
You can already pretty much do this: 

1. copy files to the destination
1. add the destination to the library
1. use the renaming from tags across all tracks to get the folder structure you want

**Comment by kellertobias** [comment]
If I am understanding the renaming track feature correctly, it only renames files, but not folders. I want a structure like artist/album/song.

Yesterday, I found `beets` for managing my music library. Might be enough for me.

**Comment by declension** [comment]
> If I am understanding the renaming track feature correctly, it only renames files, but not folders. I want a structure like artist/album/song.

No you _can_ do this, just use an absolute path e.g.:
`~/Music/<artist|<artist>|Unknown Artist>/<album|<album>|Unknown Album>/<title>`

> Yesterday, I found beets for managing my music library. Might be enough for me.

Yes, should work ([Beets uses Mutagen](https://mutagen.readthedocs.io/en/latest/#real-world-use) actually)

**Comment by CreamyCookie** [comment]
I can also highly recommend [MusicBrainz Picard](https://picard.musicbrainz.org/) if you want to first make sure the tags are correct / not missing anything and get better cover art. 

It also supports file renaming and you can define how it does so (Options > Options > File Naming). I use something like this for renaming my files.

`$if2(%albumartist%,%artist%)/$if(%date%,$left(%date%,4)) - %album%/$if($gt(%totaldiscs%,1),%discnumber%_,)$num(%tracknumber%,2) -$if(%compilation%, %artist% -,) %title%`

which creates the following folder structure

`ArtistName/2001 - AlbumName/01 - title.mp3`

or if there is more than 1 disk:

`ArtistName/2001 - AlbumName/02_03 - third title from second disk.mp3`

and you can set the destination directory, so they all end up in Quod Libet's music library.


Anyway, I'm closing this, since the requested feature is already supported. 

Feel free to ask questions here though.
