### ISSUE TITLE
Big interface

### ISSUE THREAD

**Issue by 572243** [quodlibet/quodlibet#3290]
You can reduce the scale of the interface, zoom out, font size.. in KDE fullhd this program have big interface and i can't doing nothing

in GNOME 3 i reduced the size of system fonts aaand this ~work, but anyway i have small font size everywhere
i have 1080p monitor ant information does not fit the screen
 
Thanks.

**Comment by Meriipu** [comment]
I am not superfamiliar with gtk but would using an environment variable to adjust the (font size?) of just quodlibet work, if your issue is wanting smaller text for only quodlibet ?

say, starting quod libet with:
`GDK_DPI_SCALE=0.75 quodlibet`

(from https://forum.kde.org/viewtopic.php?f=17&t=141007#p379319 )

**Comment by 572243** [comment]
thanks thks thks, that's work)
didn't know about this

**Comment by lazka** [comment]
We don't have much control over font sizes and scale factors. This should all be handled by your desktop environment.

**Comment by robgrune** [comment]
I use Kubuntu 19.10. Altering the environment fonts and scale factor has no affect upon the Quodlibet GUI.  The Quodlibet fonts remain too small. Can the fonts be set in a config file somewhere, and how to do?  Other than this limitation, Quod is great app. Very many thanks to the Quod team for this app.
