### ISSUE TITLE
Sync ratings across OSs on a multiboot machine

### ISSUE THREAD

**Issue by BraveSentry** [quodlibet/quodlibet#3426]
Hey,
I have a laptop with a Hackintosh, a Windows 10 and a Linux Mint installation. I have installed Quod Libet on all of them, and all three are pointed to the same disk partition with my music on it.

Now I rely heavily on ratings when it comes to sorting my music and I´m looking for a way to sync ratings between all three systems.

I tried the "Update Tags in Files" plugin but then can´t find a way to import these tags on the other OSs.

I also tried the "Export Metadata" plugin, but that gives me one .tags file for each song, with no possibility to do that to multiple files at once, let alone import the tags in the other OSs.

When using the "migrate metadata" plugin, the behaviour seems erratic to me: I mark a couple of tracks, press "copy", then change one songs rating, then mark the same tracks again, then paste, and the rating changes for multiple songs, and not necessarily to the rating it had, when I copied the metadata.

Any suggestions on what else I could try? Or ways I could make the things I have already tried work?

**Comment by CreamyCookie** [comment]
Ratings are stored in QL database, and while they can be stored in the files itself (I do), I think reading them isn't automatic and time intensive, so that you wouldn't want to do that every time you start QL.

I think one way that could work is copying the `.quodlibet/songs` file (QL database of songs) to an external exFAT-formatted disk?  (If you want to try, you likely need to install the format: `sudo apt-get install exfat-fuse exfat-utils`)

Then when you start, you'd need to mount the disk, copy (and replace) the `songs` file to the platform-specific QuodLibet directory. On exit, you'd copy (and replace) the `songs` file on the external disk.

I don't think it would work well to keep the whole QL directory on an external disk (e.g. file paths in playlists differ between platforms), but I could be wrong.

Please make backup of all relevant files before trying this.

**Comment by CreamyCookie** [comment]
Ratings are stored in QL database, and while they can be stored in the files itself (I do), reading them isn't automatic and checking every single file would take too much time.

Sadly, the songs database doesn't seem to be platform independent, so copying that doesn't seem to be an option.

The best way I can think of is via plugins:

1. Download my auto_update_tags_in_files.py plugin: https://gist.github.com/CreamyCookie/60f007490486d09a174a87c0f7486954 (and change it's config to your liking)
2. Modify it so that it writes a file `{song filename}.changed` in the directory of the album/song whenever ratings are written to their files (in `_write_tags_to_files`)
3. Create a plugin that runs on the start of QL (or add to the above) and goes through the whole library. Wherever it finds the `.changed` file, it deletes it, and adds the respective `SongWrapper` object to a list. At the end, call `_inform_library_of_changed` with that list. (actually just `library.reload` on each should be enough) 


```python
 	def _inform_library_of_changed(library, songs):
	    changed = []
	    for song in songs:
	        if song._was_updated():
	            changed.append(song._song)
	        elif not song.valid() and song.exists():
	            library.reload(song._song)
	    library.changed(changed) 
```

**Comment by bassstorm** [comment]
> checking every single file would take too much time

But that already happens in order to check updated 'regular' tags, doesn't it? Why rating is any different?

My use case is that when at work I use other software which could add/update RATING in the way QL does (_RATING:your@email.com_). It would be really great to see such external changes visible at home when using QL. Now I have to recall what was played and do synchronization manually. That gets worse if I play some random stuff :(
Assuming there's a timestamp against each track in the QL DB, we could compare it with file modification timestamp and take what's latest.

**Comment by CreamyCookie** [comment]
> But that already happens in order to check updated 'regular' tags, isn't it? Why rating is any different?

Does it? I thought tags are only read once when a file is added, or maybe when you play the file.

>  Assuming there's a timestamp against each track in the QL DB, we could compare it with file modification timestamp and take what's latest.

There's definitely the `lastplayed` time, but there might be an internal time as well.

**Comment by BraveSentry** [comment]
Sorry for all the time passed since I opened this, but I had a lot of stuff to do, and no time to look into this anymore. 

Thank you, CreamyCookie, for your suggestion, but I think even with (a little) more time on my hands, what you suggest goes beyond my coding capabilities.

Now I've spent a lot of time on MacOS and am now not looking for an automated solution: A one-off transferring of ratings would be enough for me, but nothing I've tried seems to work.

**Comment by bassstorm** [comment]
@CreamyCookie yes, sure. It performs library scan at startup. And also there's plugin to monitor file system for changes on the fly (via pyinotify). One could manually rescan specific song(s) via context menu as well. But unfortunately all these methods doesn't re-read rating tags.

**Comment by CreamyCookie** [comment]
@BraveSentry No problem.

I'll try to look into it when I have time, but I need more information:

@bassstorm 

Just to be clear: Do both use either the update tags plugin (on files you've rated) or the auto_update_tags_in_files plugin? 

If you do, I think it should be possible to use the [file modification date](https://stackoverflow.com/a/52858040) as @bassstorm suggested. Although that solution would not be ideal, since you'd have to go through every file in the library.


> And also there's plugin to monitor file system for changes on the fly (via pyinotify

That's surprising. I don't know how that plugin works, but I'd have guessed that and rescanning would work.

**Comment by BraveSentry** [comment]
The last thing I tried was completely removing QL from Mint (including .quodlibet folder), then in Mac running update tags in files on the complete library, then reinstalling QL on Mint, changing the email for the updated tags (a concept I not rly understand btw.) and rebuilding the library. The ratings still are the same as before.

As for the auto_update_tags_in_files plugin, I tried moving it to a newly created ~/.config/quodlibet/plugins as stated [here](https://quodlibet-frestr.readthedocs.io/en/latest/development/plugins.html), but don't see any changes in the plugin list.

**Comment by CreamyCookie** [comment]
@BraveSentry 

Hmm, doesn't seem so: https://quodlibet.readthedocs.io/en/latest/guide/faq.html?highlight=OS%20X#where-does-quod-libet-store-all-its-metadata

In the lower left of the plugin window, is there maybe an error button?

**Comment by BraveSentry** [comment]
There is no error button. What also seems strange to me: I tried finding the location where the pre-installed plugins are stored, in order to try and paste your plugin there. I could not find them anywhere, at least not on Mac, even including hidden files and system files, and using the Find Any File tool. I have not looked into the other OSs yet.

**Comment by bassstorm** [comment]
I actually decided to isolate my use case with file tags (see #3561). As multi-boot system seem to be more related to library data storage, though still related of course.

**Comment by CreamyCookie** [comment]
@bassstorm Makes sense!

@BraveSentry Hmm.. Weird. Could you run Quodlibet in the command line and post the output here? 

Have you put the plugin in `~/.quodlibet/plugins`? (To my knowledge, `~/.config/quodlibet/plugins` only works in Linux.)

**Comment by BraveSentry** [comment]
I had not put it there, as this information did not seem to be out there. Now I have added your plugin to that folder, and it shows up in QL (hooray!). - But that plugin only uses the same mechanism as Update tags in files, which doesn't seem to work for me.

Starting QL from the command line gives me no output on mac. On Mint, it's this, omitting repeated lines:

```
E: 26.653: formats._misc.MusicFile: aiff.py:237:load: quodlibet.formats._misc.AudioFileError: '/mnt/044A4C273A322D33/Musik/14_10_Kantcheli2.aif' ID3v2.32 not supported # Note that this line is not repeated.
E: 26.656: formats._misc.MusicFile: _util.py:559:<lambda>: quodlibet.formats._misc.AudioFileError: unpack requires a buffer of 4 bytes
E: 26.669: formats._misc.MusicFile: __init__.py:402:__init__: quodlibet.formats._misc.AudioFileError: can't sync to MPEG frame
E: 26.671: formats._misc.MusicFile: wave.py:269:_read_fmt_chunk: quodlibet.formats._misc.MutagenBug: unknown format: 85
E: 26.671: formats._misc.MusicFile: wave.py:269:_read_fmt_chunk: quodlibet.formats._misc.MutagenBug: unknown format: 2
E: 26.871: formats._misc.MusicFile: _tags.py:74:__init__: quodlibet.formats._misc.AudioFileError: Header size not synchsafe # Note that this line is not repeated.
```

**Comment by CreamyCookie** [comment]
> But that plugin only uses the same mechanism as Update tags in files, which doesn't seem to work for me.

What do you mean by that? I know that it doesn't solve the transfer problem itself, but it's the first step.

Once the ratings and playcounts are stored in your files (assuming they're of a format that supports it: mp3, ogg, opus, flac), we can then figure out how to reload the ratings in QL in some way.

**Comment by BraveSentry** [comment]
Well, searching the docs for "plugin", you only get the path for linux systems, not mac, so naturally, I put it there.

As for the file formats: It's a mixed bag, with a vast majority of mp3, a portion of m4a, some wav, ogg, aiff and others. As I commented on the log: The one line concerning the aiff was the only one mentioning unsupported tag formats.

> What do you mean by that? I know that it doesn't solve the transfer problem itself, but it's the first step.

What I meant was that I could not see a path going on from this first step.

**Comment by declension** [comment]
I'm not sure what the current state of this issue is / should be - anyone got any opinions?

(To me syncing ratings best done in the file, except for a bunch of bugs and gotchas, but they're being solved slowly..)

**Comment by CreamyCookie** [comment]
@declension Have not tested this extensively, but it seems there is no way to make QL reload ratings from the file via the UI, so the solution is to fix that and/or have some way to import/export ratings (something I'm close to finishing - it does more than import/export ratings - not looking forward to creating the rest of the UI for it though :sweat_smile: )

**Comment by declension** [comment]
Thanks @CreamyCookie. Worth having another look, I pushed a fix in #3618 that might fix some underlying problems here

**Comment by bassstorm** [comment]
> To me syncing ratings best done in the file

More than agree. Visible to other software, requires no extra manual actions, and always in place even if QL config is lost.

**Comment by CreamyCookie** [comment]
@declension Awesome change! I'm closing this for now. 

@BraveSentry  (and other users affected) 

Feel free to comment here if this is still an issue and I'll reopen!

**Comment by CreamyCookie** [comment]
Hmm.. I had a bit of a trigger finger there. I'll guess there's the problem of file types that don't support ratings in files though few people use them probably. 

And a manual action is required, but on the other hand, automatically reloading every file at the start would be really bad, and probably not that many people use QL across multiple OSes.

So, I'm unsure whether it should stay open or not, but still leaning towards closed so I leave it at that.
