### ISSUE TITLE
Python syntax error on apt upgrade from 4.3 to 4.4

### ISSUE THREAD

**Issue by sidneygijzen** [quodlibet/quodlibet#3606]
Steps to reproduce
------------------
`sudo apt update` reported there was an update available for Quod Libet  / Ex falso. I'm using the PPA `http://ppa.launchpad.net/lazka/ppa/ubuntu`. I tried to upgrade by running `sudo apt upgrade` 

Expected Output
---------------
I expected Quod Libet to upgrade without any problems.

Actual Output
-------------
The upgrade failed due to a Python syntax error. The following message appears 3 times:
```python
  File "/usr/lib/python3/dist-packages/quodlibet/query/_match.py", line 12
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
```
See the complete log below (heading 'Additional Information')

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Kubuntu 18.04

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
The following output displays while trying to upgrade:

```
Get:1 http://ppa.launchpad.net/lazka/ppa/ubuntu bionic/main amd64 quodlibet all 4.4.0-0~ppa0~bionic [79,5 kB]
Get:2 http://ppa.launchpad.net/lazka/ppa/ubuntu bionic/main amd64 python3-mutagen all 1.45.1+2-0~ppa2~bionic [146 kB]
Get:3 http://ppa.launchpad.net/lazka/ppa/ubuntu bionic/main amd64 exfalso all 4.4.0-0~ppa0~bionic [1132 kB]
Fetched 1357 kB in 0s (3038 kB/s)
(Reading database ... 311293 files and directories currently installed.)
Preparing to unpack .../quodlibet_4.4.0-0~ppa0~bionic_all.deb ...
Unpacking quodlibet (4.4.0-0~ppa0~bionic) over (4.3.0+2-0~ppa2~bionic) ...
Preparing to unpack .../python3-mutagen_1.45.1+2-0~ppa2~bionic_all.deb ...
Unpacking python3-mutagen (1.45.1+2-0~ppa2~bionic) over (1.45.1+1-0~ppa1~bionic) ...
Preparing to unpack .../exfalso_4.4.0-0~ppa0~bionic_all.deb ...
Unpacking exfalso (4.4.0-0~ppa0~bionic) over (4.3.0+2-0~ppa2~bionic) ...
Setting up python3-mutagen (1.45.1+2-0~ppa2~bionic) ...
Setting up exfalso (4.4.0-0~ppa0~bionic) ...
  File "/usr/lib/python3/dist-packages/quodlibet/query/_match.py", line 12
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined

  File "/usr/lib/python3/dist-packages/quodlibet/query/_query.py", line 11
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined

  File "/usr/lib/python3/dist-packages/quodlibet/util/collection.py", line 11
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined

dpkg: error processing package exfalso (--configure):
 installed exfalso package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of quodlibet:
 quodlibet depends on exfalso (= 4.4.0-0~ppa0~bionic); however:
  Package exfalso is not configured yet.

dpkg: error processing package quodlibet (--configure):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60ubuntu1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 exfalso
 quodlibet
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by declension** [comment]
It looks like you're on Python 3.6 perhaps?

As [4.4.0 now needs 3.7+](https://quodlibet.readthedocs.io/en/latest/changelog.html#perfection-is-back-on-the-menu), the workaround is to install Python 3.7 or newer.

Perhaps this should form part of the apt dependencies @lazka?

**Comment by lazka** [comment]
ah I missed that

**Comment by dannn-o** [comment]
Hit this as well on Linux Mint 19.3 (Python versions installed are 2.7.17 and 3.6.9).  I've been burned a few times by apps needing an upgraded version of Python installed (i.e. had to restore the most recent system image from Clonezilla to get a bootable system), so want to proceed with caution in trying to fix or work around this bug.

Any suggestions would be appreciated.

**Comment by dannn-o** [comment]
Update:  Tried installing Python 3.7.5 and making that the default version for Python3:

> $ python3 -V
Python 3.7.5

However, the PPA installation is still failing with the same error referenced by the OP:

> Setting up exfalso (4.4.0-0~ppa0~bionic) ...
  File "/usr/lib/python3/dist-packages/quodlibet/query/_match.py", line 12
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined

**Comment by declension** [comment]
Thanks @dannn-o . How did you set the default `python3`? Did you also set the default for `python`? For some reason, looks like the old version of Python is still being invoked by `apt`, as 3.7.5 definitely understands that import:

```bash
$ docker run python:3.7.5 python -c 'from __future__ import annotations' && echo SUCCESS
SUCCESS
 ```

side note: no idea why it's executing that code just to install...

**Comment by sidneygijzen** [comment]
Thanks for the quick responses @declension and @lazka. And thank you @dannn-o for testing the workaround. 

> It looks like you're on Python 3.6 perhaps?

Correct. `python3 -V` returns `Python 3.6.9`. 

> As [4.4.0 now needs 3.7+](https://quodlibet.readthedocs.io/en/latest/changelog.html#perfection-is-back-on-the-menu), the workaround is to install Python 3.7 or newer.

Thanks for the clarification. I am always very hesitant in upgrading system defaults for the reason mentioned above by @dannn-o.

> Perhaps this should form part of the apt dependencies @lazka?

Another suggestion: pin the version to 4.3.0 on bionic? And release 4.4.0 on distributions which support Python 3.7 out-of-the-box?

**Comment by lazka** [comment]
I've reverted bionic to 4.3

**Comment by dannn-o** [comment]
Thanks, @lazka , for reverting to 4.3.  As for my misplaced bravery:  I've burned myself again with installing Python3.7.  It broke Cinnamon, and even after using Synaptic to uninstall it and force a reinstallation of 3.6 (just for precaution), I can only get it to load the desktop successfully by using "software rendering" mode.

@declension - I had used the 

> sudo update-alternatives --config python3

command to set 3.7 as the preferred/default Python3 version.  Obviously, that wasn't sufficient and didn't leave 3.6.9 in a usable state.

So, my plan is to back up my files added since my last system image and nuke-and-pave.  Unless someone has a suggestion that might work to salvage Cinnamon........

**Comment by dannn-o** [comment]
A bit unrelated, but some good news:  I had everything set to go with the nuke-and-pave, and then I thought to double-check my Timeshift config.  There happened to be a snapshot from the day before I made the Python changes, so I figured I had nothing to lose...

The Timeshift restore helped get my PC going again (only minor issue is that it made the system temporarily unbootable by messing up GRUB, but I corrected that fairly easily using a bootable USB drive with the Boot Repair utility installed).  

Back to the Python issue:  The PPA is no longer trying to install Quod Libet 4.4, but Mutagen 1.45.1+2-0~ppa2 is queued up from the PPA.  Is the Mutagen update safe if staying at Quod Libet 4.3? 

Regarding Flatpak:  I have steered clear of that because of the ridiculous package sizes and disk space required (Quodlibet is 798.2 MB and 2.7 GB respectively!), but on top of that I'd hate to have to start from scratch by reloading my entire library, reconfigure all of the plugins I use, etc.  Is there a chance the PPA can somehow address the Python dependency change in the future, or is Flatpak really the only options for staying current (outside of upgrading to a newer OS version)? 

Thanks - I only ask because Quod Libet is an essential app for me!!

**Comment by lazka** [comment]
There is no supported way to update a system Python manually. You can update to Ubuntu 20.04 though.

mutagen still supports Python 3.6

**Comment by lazka** [comment]
@dannn-o you can share the config between the flatpak and host app: https://quodlibet.readthedocs.io/en/latest/development/flatpak.html?highlight=flatpak

**Comment by sidneygijzen** [comment]
> I've reverted bionic to 4.3

Thank you @lazka! I was able to downgrade to 4.3 successfully. 

@dannn-o happy to hear you were able to restore your Cinnamon environment.

**Comment by lazka** [comment]
Sorry again for the breakage.
