### ISSUE TITLE
Add new logos for Quod Libet and Ex Falso

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3628]
The proposed change
-------------------
Add new logos for Quod Libet and possibly Ex Falso.

Benefits of this change
-----------------------
Gives it a more modern look. Old icons might make users think the app is not maintained anymore or it might simply not catch their eye.

Any issues this might cause
---------------------------
None really, but a few users (who are not using icon packs) might not recognize the icon at first. 

Tasks
-----------------------
1. Choose logo.
2. Replace logos in [images/hicolor/scalable/apps](https://github.com/quodlibet/quodlibet/tree/8b58a81b077e00b32cc4ad30520ccc8ca70f4406/quodlibet/images/hicolor/scalable/apps)
3. Update logo here: https://en.wikipedia.org/wiki/Quod_Libet_(software)

### Current state
![quodlibet_old_logo](https://user-images.githubusercontent.com/3063858/114902387-10027e00-9e16-11eb-8184-0aa38f723ed5.png)

### My proposal

![quodlibet (ex falso based on one not by me)](https://user-images.githubusercontent.com/3063858/115044579-ef016200-9ed5-11eb-8a6d-bab5c8f74f6c.png)

> [zipped svg](https://github.com/quodlibet/quodlibet/files/6319584/quodlibet-logo-proposal.zip) (GitHub does not allow svg to be uploaded) if you want to try some changes
> Created with Inkscape.

Similarly to Ex Falso's logo I'm trying to go for a more squarish look, as that's pretty much the standard for most app icons nowadays. Consistency is awesome and looks great!

The new Ex Falso design is based on the old. Corners are rounded and the spikes are cut shorter.

How they look at a low resolution: 

![quodlibet (ex falso based on one not by me) small](https://user-images.githubusercontent.com/3063858/115044533-e315a000-9ed5-11eb-9d6c-cc2b7e90a32e.png)

I'd be interested in any feedback. It's totally okay if you don't like one or both, and it's fine if someone else's icon would be chosen. :slightly_smiling_face:

**Comment by bassstorm** [comment]
Last from three looks slightly better to me. But I feel it would be also interesting to come up with something completely different.

**Comment by CreamyCookie** [comment]
@bassstorm Thanks for the feedback! I'd be open to that, though, of course, there are also huge benefits to choosing an icon similar to the current one. (Easier to recognize, for example)

**Comment by fitojb** [comment]
Making both logos have a similar visual weight to each other is a welcome improvement.

**Comment by KarimbaYo** [comment]
Hi,

I really approve @CreamyCookie's idea of optimizing the app icons, and I would like to add some proposals to broaden the discussion:
![quodlibet_proposals_210714](https://user-images.githubusercontent.com/87414867/125609880-9152f6df-4ae7-40f4-a079-89b3b6749f5a.jpg)
**1:** A really simple and contrasted proposition that keeps the original petrol blue gradient as solid background, and initial letters of app names (QuodLibet and ExFalso) in a new font integrating the current (and optimized) icons.

**2:** I reused the current logos and added the _less-_ and _greater-than_ signs, typical of [code icons](https://www.google.com/search?q=code%20file%20icon&tbm=isch&tbs=isz:i&hl=fr&sa=X&ved=0CAQQpwVqFwoTCKCAp7mw4vECFQAAAAAdAAAAABAC&biw=1599&bih=866), because the tag syntax (and query language) is an important and specific feature of QuodLibet. The background shape follows these tags and is unique enough to be quickly recognized.

**3:** This cylindrical one can be seen as a [standard database icon](https://www.google.com/search?q=database+icon&sxsrf=ALeKk00az8HY8DEaCxpj1dLP9VnPP2mJfA:1626255256651&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjbyIv3oOLxAhUo4YUKHQIDBnoQ_AUoAXoECAIQAw&cshid=1626255321979260&biw=1599&bih=866&dpr=2) (because QL aims at huge music collections) and as a vinyls stack (which are the collectors' typical media).

**4:** I was looking for a musical notation symbol that best expresses the Quod Libet meaning “whatever you please”, and found the [fermata](https://en.wikipedia.org/wiki/Fermata): a dot and an arc (or squared bridge for rest) on a staff which indicates to the performer that he can play the note as long as he wants. I turned it into a turntable for QL (the audio player), and into a vinyl sleeve for ExFalso (the tag editor).

**Comment by declension** [comment]
Closing this as done for now, we have some new logogs
