### ISSUE TITLE
Ex Falso: Preferences interface doesn't open (AssertionError)

### ISSUE THREAD

**Issue by City-busz** [quodlibet/quodlibet#3711]
After applying https://github.com/quodlibet/quodlibet/commit/d96634d95fda69110722bf14716eacf329d63438 for version 4.4.0, I still unable to open the preferences window.
```
AssertionError: 
------
Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/quodlibet/qltk/exfalsowindow.py", line 75, in prefs_cb
    window = PreferencesWindow(self)

  File "/usr/lib/python3.9/site-packages/quodlibet/qltk/exfalsowindow.py", line 294, in __init__
    self.use_header_bar()

  File "/usr/lib/python3.9/site-packages/quodlibet/qltk/window.py", line 179, in use_header_bar
    assert not self._header_bar

AssertionError

```

**Comment by declension** [comment]
How are you running QL? That seems like a distribution version not a local (dev) check-out?

**Comment by City-busz** [comment]
I'm using version 4.4.0 on Arch Linux with the patch applied. Are there any other fixes are available for this problem on git dev?

**Comment by declension** [comment]
> Are there any other fixes are available for this problem on git dev?

Not AFAIK, but taking individual changesets is a bit unsupported. There are definitely a fair few changes to `master` since 4.4.0:
https://github.com/quodlibet/quodlibet/compare/release-4.4.0...master so plenty of potential culprits.

I guess the question is how sure are you the correct code was patched correctly? Could you try git `master` latest and see if that works?

**Comment by City-busz** [comment]
I tried the code from `git master` now, but I still get the same error.

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-Q5](https://sentry.io/organizations/quodlibet/issues/2414265250/?referrer=github_plugin)
