### ISSUE TITLE
Shuffle mode loses played-history when song list is reordered

### ISSUE THREAD

**Issue by slosd** [quodlibet/quodlibet#4108]
Steps to reproduce
------------------

1. Enable random shuffle
2. Start a song (_song A_)
3. Press "next" button
4. Sort song list by a different column so the order of the songs change
5. Press "previous" button (a second time if playback goes to the beginning of the current song)

Expected Output
---------------

Playback goes to _song A_.

Actual Output
-------------

Playback stops. UI shows "Not playing".

Test System
-----------

Quod Libet 4.5.0

Additional Information
----------------------

Because of this issue auto-sorting was disabled while shuffle mode is active in https://github.com/quodlibet/quodlibet/pull/3581. The auto-sorting feature seems to have made this bug more obvious, but it's not the root cause. This also happens when the list is manually re-sorted.

Also related: #3592

**Comment by slosd** [comment]
The reason for this is the implementation of shuffle-orders. These keep the history by referring to the row index. This becomes invalid when the rows are re-sorted. Therefor the history is reset when that happens. This is actually already described in a comment:
https://github.com/quodlibet/quodlibet/blob/3d75ddbf95c71c39ae59121424b0dd873bc808ce/quodlibet/qltk/songmodel.py#L257-L261

Here's the relevant order mixin:
https://github.com/quodlibet/quodlibet/blob/3d75ddbf95c71c39ae59121424b0dd873bc808ce/quodlibet/order/__init__.py#L102-L128

I'm wondering why this doesn't use the `TreeIter` which would remain valid as the order changes afaik.

**Comment by slosd** [comment]
@declension I just noticed #575, so I think this is actually a duplicate.

**Comment by nhf216** [comment]
I wonder if the combination of this issue and #3957 is causing the behavior from #3592 to occur in 4.5.0 in the Playlists browser.

For reference, I'm unable to play previous songs in shuffle mode from the Playlists browser, though this works fine in the Track List browser (as long as I don't reorder the tracks). I recently upgraded from an old version (don't remember which one) to 4.5.0 along with an upgrade from Ubuntu 20.04 to 22.04. I had a similar issue (or the same issue) in that version as well as the one I used on Ubuntu 18.04. I do **not** have this issue on Windows 10 in 4.3.0.

I used to rely on the behavior from #3041 as a workaround. (Start playing the playlist, then return to Track List browser while playlist remains displayed. Previous worked fine there in shuffle mode.) This is no longer an option, nor is the Shuffle Playlist plugin (because of #3957).
