### ISSUE TITLE
Error when Disc column is hidden and a tag pattern is used instead

### ISSUE THREAD

**Issue by Miss-Inputs** [quodlibet/quodlibet#4164]
Steps to reproduce
------------------
- Add a new column: `<~#discs|<~#disc> of <~#discs>|<~#disc>>`
- Move this column to the leftmost position
- Hide the Disc column
- Hide the track number column as well?

Expected Output
---------------
No error message. If it turns out this tag pattern is invalid, I would expect it to tell me that

Actual Output
-------------
The column does display something like "1 of 1" (or just 1 for files with the disc total tag not set), but an error message appears every time a new song starts playing (related to #3957):
```
NameError: name 'v0' is not defined
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/qltk/quodlibetwindow.py", line 1338, in __browser_cb
    self.songlist.set_songs(songs, sorted)

  File "/usr/lib/python3/dist-packages/quodlibet/qltk/songlist.py", line 830, in set_songs
    default = self.find_default_sort_column()

  File "/usr/lib/python3/dist-packages/quodlibet/qltk/songlist.py", line 523, in find_default_sort_column
    if not get_sort_tag(c.header_name):

  File "/usr/lib/python3/dist-packages/quodlibet/qltk/songlist.py", line 170, in get_sort_tag
    tag = Pattern(tag).format

  File "/usr/lib/python3/dist-packages/quodlibet/pattern/_pattern.py", line 371, in Pattern
    cache[(Kind, string)] = Kind(func, list_func, tags)

  File "/usr/lib/python3/dist-packages/quodlibet/pattern/_pattern.py", line 193, in __init__
    self.format(self.Dummy())  # Validate string

  File "/usr/lib/python3/dist-packages/quodlibet/pattern/_pattern.py", line 245, in format
    value = u"".join(self.__func(self.SongProxy(song, self._format)))

  File "<string>", line 6, in f

NameError: name 'v0' is not defined
```

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Xubuntu 22.04

### If it's audio-related, what back-end?
Prooobably not audio related? But gstreamer 1.20.3

Additional Information
----------------------
This one's weird and hopefully makes sense. I was just trying to have a "Disc X of Y" column, guess I could have used `~#disc~~#discs~` but I was being a fussy little bastard about the separator, which doesn't seem to be changeable from what I can tell. Tried to find other conditions where this happens other than this one specific thing, but no luck.

**Comment by afontenot** [comment]
Thanks for the report!

Your tag is fine. The reason you get errors when you do is because the error appears when trying to sort by the column you created. You then see it whenever advancing the track list because the sorting function is called to determine which song is next in the list.

The issue here is that Quod Libet tries to do a bit of magic when you sort by a column - doing what you mean rather than what you say. 

For example, sorting by the track column doesn't actually sort by the track column. That's because the song view can have multiple albums from multiple artists, all shown at once, and almost always when a user wants to sort by track number, what they want is actually sorting by album, then by disk, and *then* by track number, so that's what we do. Clicking the track column just tells Quod Libet "do the default sort".

In your case, I think you also probably want the default sort (which looks at disc number). Correct me if that's wrong.
