### ISSUE TITLE
Drag and drop in a playlist browser causes the playlist to re-display at the start

### ISSUE THREAD

**Issue by lbt** [quodlibet/quodlibet#4179]
Steps to reproduce
------------------
Open a playlist with more tracks than fit in the view.
Scroll down
Use drag and drop to re-arrange a track.

Expected Output
---------------
Drag and drop works and the playlist remains at the same scroll position
This is what happens at e5a2e93ac31f22a69a0ef0c92e3a3e004f8dd2aa

Actual Output
-------------
Drag and drop works and the playlist scrolls to the start
This happens at feed5c88e0d039d1895fa1e833e6c22980f859b2

Test System
-----------

### Which version of Quod Libet?
git master

### Which operating system 
Debian

### If it's audio-related, what back-end?

Additional Information
----------------------

A bisect shows this is caused by PR#4075

Specifically the .activate() here:

https://github.com/quodlibet/quodlibet/pull/4075/files#diff-923db7bb34d8d3f6013ae68b097606ded600393ad3e93d7ca6a1eb1d2a2f3391R140

**Comment by lbt** [comment]
Investigating:
```
        self._swin = self.__embed_in_scrolledwin(view)
```
and 

```
+                        scroll_pos = self._swin.get_placement()
                         self.activate()
+                        self._swin.set_placement(scroll_pos)
```

but that doesn't work...  not sure how to handle this in Gtk :)

**Comment by lbt** [comment]
OK ... it should be get/set_h/vadjustment() I think.

But even then the activate just emits a signal 'later' so the set_h/vadjustment() needs to be after the signal is handled.

**Comment by lbt** [comment]
@declension just mentioning you here as you may have some insight into why your commit seemed to break this :)

**Comment by Meriipu** [comment]
If it is what I think, try commenting out 
```
                    if playlist is current:
                        self.activate()
```
in `quodlibet/browsers/playlists/main.py`

https://github.com/quodlibet/quodlibet/commit/e54ec9828413e5f8a59c04ef0f076bd7bf484e5e

it fixes some really minor bug that I personally do not care about since it has an easy workaround (select a different playlist and select the main playlist again toe refresh it) while it reintroduces a lot of annoying ones that I really care about (the playlist scrolls back to the top all the time)

the bug that adding `self.activate()` fixes is https://github.com/quodlibet/quodlibet/issues/4072 - but in my opinion it is not very common to care about the scroll-position immediately after adding new songs, as you are usually adding many songs.

**Comment by declension** [comment]
IIRC yes there are two bugs whose fixes are pretty much mutually exclusive, without a total rewrite, so here we are. If the other one (lack of updates using secondary browsers etc in #4072) is generally thought to be less of a pain then we could revert.

**Comment by everdred** [comment]
I was going to open an issue for the scroll-to-the-top behavior I see when removing one or more tracks from a long playlist, but it sounds like this is probably the same issue.

**Comment by robertmuth** [comment]
Please, pretty please, apply Meriipu's patch.

My use case is curating multi-hour playlist and quodlibet has become completely useless with this bug.

**Comment by declension** [comment]
This is now done, but with the predicted problems.
