### ISSUE TITLE
Search for artist also returns album

### ISSUE THREAD

**Issue by zz0rk** [quodlibet/quodlibet#4355]
Steps to reproduce
------------------
Search for artist
&(artist = "Vader")

Expected Output
---------------
Only results for the artist (Vader) would be returned.

Actual Output
-------------
Results also included albums (Vader) that shared the same name as the artist.

### Which version of Quod Libet?
4.3.0

### Which operating system 
Debian 11

Additional Information
----------------------
See screenshot

![image](https://github.com/quodlibet/quodlibet/assets/18619265/33dedb92-ba52-436b-ab55-6804d57f0826)

**Comment by declension** [comment]
I don't see any Album titles with `Vader` in them there though.

Also, are these the same results as just `artist= "Vader"`?

**Comment by zz0rk** [comment]
I was wrong. What happens is that a search for an artist may include results of albums by other artists who share the same album title. In this example a search for 'Vader' includes search results for an album 'De Profundis' (artist: Vader, After Crying).


![image](https://github.com/quodlibet/quodlibet/assets/18619265/b376f6f1-031a-4fc5-82d5-44dfc28934b7)

**Comment by declension** [comment]
Thanks, sorry about the delay. This is actually expected behaviour.
The best way to think of it is:

* that album query is pulling back any album whose _collection aggregate_ matches `artist=vader`. 
* For the `artist` tag (and similar), this aggregate is an _union_ type of aggregation, 
* Thus, _De Profundis_ is selected as the albums artists are _After Crying, Vader,..._
* However (confusingly) when you look at the tracks themselves in the Album browser, _they_ are not being filtered by that query (that's what the _Track List_ browser is for

Hope that helps
