### ISSUE TITLE
Shuffle mode causes segfaults

### ISSUE THREAD

**Issue by Konzertheld** [quodlibet/quodlibet#4373]
Steps to reproduce
------------------
Start QL, try to play some songs in peace

Expected Output
---------------
Songs are played until I decide not to or playlist is empty

Actual Output
-------------
After two songs, playback stops. It's always after two songs. In a lot of cases, QL also crashes. When restarted, it has one of these "an issue has occured, you can continue to use QL but it may be unstable" things. When I press restart, QL starts without issues but apparently the database has not been saved: The songs that played last have no updated "last played" timestamp. Also, the search bar does not contain the search string that it contained last (I always use QL in search library mode).

Test System
-----------

### Which version of Quod Libet?
4.6

### Which operating system 
SteamOS (Arch Linux)

### More
It might be relevant that the file system the songs are on is btrfs. QL was installed as Flatpak.

**Comment by declension** [comment]
Thanks for filling. Did you submit the crash reports? (there are a few similar ones, so will link here if so). 
Without details of what the "crash" was it's hard to say, but there are a few segfaults that have been happening in GTK+ code for people. Unfortuantely there's often less we can do about these but the first thing is getting the logs

**Comment by Konzertheld** [comment]
I am not sure about past crash reports but I submitted one now and added the link to this ticket to it.

I would like to point out though that QL does not always crash. In about half the cases it just stops playing after two songs.

**Comment by lbrueckner** [comment]
I've the same issues since I've updated to 4.6 a couple of days ago.

I noticed that the playback stops and occasional crashes after the second song only then occur (for me) when 

a) I listen on shuffle and 
b) the track list is filtered in a way that the just finished song gets removed, i.e. with a filter like `#(lastplayed > 10 days)`. 

Then the crash always happens in `"quodlibet-4.6.0/quodlibet/order/__init__.py", line 136 in get_index`. I have already submitted some crash reports on this ;-)

**Comment by Konzertheld** [comment]
I can confirm that QL does not stop playback or crash for me when I remove the `#(lastplayed > X)` filter. Shuffle is okay.

**Comment by Oldbwl** [comment]
I too suffered the same issue  - crash report(s) submitted. I am playing a saved search to play only items which have not been played before, the filter is set to prefer the lower playcounts as well.

For now I have had to regress to v 1.4.0 from the Linux Mint Repos.

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-12N](https://quodlibet.sentry.io/issues/4502508589/?referrer=github_plugin)

**Comment by Oldbwl** [comment]
After doing some tests, V4.6.0 saved searches do stop after 2 or sometimes 3 tracks, but only when my system has the Shuffle Mode toggled on . Turning that off and play continues continuously. For reference I am using Linux Mint Cinnamon 21.2.

**Comment by declension** [comment]
I'm pretty sure this is down to #4255 

We'll have to find a fix or revert this

**Comment by declension** [comment]
Anyone who can - please try pulling latest `main` (see https://quodlibet.readthedocs.io/en/latest/development/devenv.html perhaps) and seeing if the problem is gone (albeit with the original shuffle bug back)

**Comment by lbrueckner** [comment]
I can confirm that the problems have disappeared

**Comment by Konzertheld** [comment]
Interesting - so the fix for the shuffle bug introduced problems that go away if shuffling is deactivated but also if `#(lastplayed)` is not used (but shuffle is still on).

**Comment by declension** [comment]
Hi - could anyone affected by the original bug (on Arch I guess) try the branch in PR #4405? :pray:

**Comment by lbrueckner** [comment]
I'm on Ubuntu, not on Arch, and was affected by the the original bug.

I've cloned slosd / quodlibet and used the fix-shuffle-history-2 branch for an hour. I've shuffeled with a reducing playlist filter `#(lastplayed>5 years)` and it ran stable, no crashes 🥳

I've also noticed that the behavior of the playlist info at the bottom right edge i.e. "3.581 songs (9 days, 13 hours)" has also changed. Without the fix the info was updated when I've changed the sort order of the playlist. With the fix it didn't update at all. I suspect this is expected behavior, but I'd love when the info would get updated whenever a track finish and disappears from the playlist.

**Comment by declension** [comment]
Thanks @lbrueckner

**Comment by Konzertheld** [comment]
Hi, assuming the fix is in QL 4.6, I can not confirm that the problem is solved. I still have the exact same issue. That is on SteamOS which is Arch-based using the Flatpak.

**Comment by LoveIsGrief** [comment]
When will this be released? The last release was in August and I'm currently suffering from this.

**Comment by Oldbwl** [comment]
Please, Can the PPA be updated to include the fix, I am stuck on 4.4.0 from the Mint/Ubuntu repo's and use the "Shuffle/Prefer less rated" a lot, On the PPA install the QL app crashes after the 2nd file played. I cant install or run from Github on my PC's
