### ISSUE TITLE
[Queue Only] Shuffle mode toggle not persisted between sessions

### ISSUE THREAD

**Issue by timmy31113** [quodlibet/quodlibet#4410]
When the shuffle mode is set to Queue Only, the shuffle mode on/off toggle will be reset when closing QuodLibet.

Steps to reproduce
------------------
0. (Make sure the Queue Only plugin is enabled)
1. Open Quod Libet
2. Enable the Shuffle mode toggle and select Queue Only from the dropdown
![Bildschirmfoto_2023-10-23_13:50:45](https://github.com/quodlibet/quodlibet/assets/43409369/972fcf29-4e7a-4e6b-9581-631b985bf6de)
3. Close Quod Libet
4. Open it again

Expected Output
---------------
The Shuffle mode toggle should be enabled.
Double clicking a song in the browser should enqueue it.

Actual Output
-------------
The Shuffle mode toggle is disabled.
![Bildschirmfoto_2023-10-23_13:51:40](https://github.com/quodlibet/quodlibet/assets/43409369/44915c5f-9c42-434f-ad26-4efbe9e67a88)
Double clicking a song in the browser plays it and ignores the queue.

Test System
-----------

Quod Libet version
4.6.0 (from Arch Linux repos `quodlibet 4.6.0-1`)

Operating system
Arch Linux

Additional Information
----------------------
Debug log:
```
…
👉 enabling shuffle mode toggle:
D: [0007.684] qltk.playorder.__compose_order: Updating PlaylistModel order to <Nur Warteschlange>
👉 closing the Quod Libet window:
D: [0013.693] qltk.window.__restore_state: Restore state
D: [0013.694] qltk.window.__restore_position: Restore position
D: [0013.694] qltk.window.__restore_size: Restore size
D: [0013.694] main.before_quit: Saving active browser state
D: [0013.695] main.before_quit: Shutting down player device 'GStreamer: 1.22.6.0'.
D: [0013.696] player.gstbe.player.__destroy_pipeline: Destroying Gstreamer pipeline
D: [0013.698] PluginManager.save: Saving plugins: 2 active
D: [0013.698] PluginManager.enable: Disable 'WaveformSeekBar'
D: [0013.699] PluginManager.enable: Disable 'queue'
D: [0013.699] qltk.playorder.__compose_order: Updating PlaylistModel order to <Normal>
D: [0013.700] _main.quit_gtk: Quit GTK: done.
D: [0013.714] PlayQueue._write: Saving play queue after 12.9s
D: [0013.714] qltk.queue.__destroy: Stopped autosave
D: [0013.716] _main.run: Gtk.main() done.
D: [0013.727] FSInterface.destroy: Disconnecting signal 3577 from <SongFileLibrary @ 0x7fa242466f40>
D: [0013.727] library.save: Saving all libraries...
D: [0013.728] SongFileLibrary.save('main'): Saving contents to '/home/tim/.config/quodlibet/songs'
D: [0014.361] library.destroy: Destroying all libraries...
D: [0014.361] SongFileLibrary.stop_watching('main'): Removing watches on 0 dirs
D: [0014.361] SongFileLibrary.stop_watching('filesystem'): Removing watches on 0 dirs
D: [0014.361] config.save: Writing config...
D: [0014.364] main.main: Finished shutdown.
``` 

**The core (non-plugin) shuffle mode settings are not affected by this behavior, i.e. the shuffle mode toggle keeps its state between application restarts when one of the normal shuffle modes is selected.**

In the config file, the key `shuffle` is changed to `False` on application shutdown. The key `shuffle_mode` stays at the user-selected value `Nur Warteschlange`

`Nur Warteschlange` is the German localization for Queue Only

**Comment by JamesDBartlett3** [comment]
I'm experiencing this same bug in Quod Libet 4.6.0 on both Windows 10 and Windows 11.
![image](https://github.com/quodlibet/quodlibet/assets/37491308/6336cde6-399c-4cf5-8664-e9ee3b35b194)

I have discovered what I believe to be a significant clue as to what might be causing this issue. It seems that the shuffle toggle only resets to "Off" on quit when the "Prefer less played" shuffle type (from the Playcount Equalizer plugin) is selected. 
![image](https://github.com/quodlibet/quodlibet/assets/37491308/6a605ffa-7077-4545-934c-ac98849f3825)

If I set the shuffle type to either of the two standard options ("Prefer higher rated" or "Random"), then the shuffle toggle remains enabled after quitting and re-launching Quod Libet.
![image](https://github.com/quodlibet/quodlibet/assets/37491308/20a98214-7eb6-43a4-aaf7-c56acb48afe5)

This leads me to suspect that the issue is being caused by a conflict between Quod Libet's native shuffle settings and the Playcount Equalizer plugin's shuffle settings, but I'm not sure where to begin looking for this potential conflict in the code.

**Comment by toy** [comment]
As already noted by @JamesDBartlett3 it is most probably a duplicate of #4184

**Comment by timmy31113** [comment]
I am still a noob issue opener, let me try to close this issue and mark it as a duplicate of #4184

**Comment by timmy31113** [comment]
Duplicate of #4184
