### ISSUE TITLE
Sort by Track ID not working as intended 

### ISSUE THREAD

**Issue by xade93** [quodlibet/quodlibet#4542]
Steps to reproduce
------------------
1. Add "Track" Entry to tab.
2. Sort by track

Expected Output
---------------
Sorted by numerical order

Actual Output
-------------
![image](https://github.com/quodlibet/quodlibet/assets/24752033/7278fd9c-027a-4270-bab9-d80c4d84ca32)

Test System
-----------

### Which version of Quod Libet?
4.6.0-2

### Which operating system 
Arch

### If it's audio-related, what back-end?
NA

Additional Information
----------------------
Apparently this only happens over certain songs, I dont know why. Could be metadata-parsing related issue?

**Comment by gevhaz** [comment]
Does it sort primarily by album and then only within the album sort it by track numbers? Looks like that's what it does in my case.

I've also had issues with track sorting where it seems entirely random, but curiously only in the 'File System' browser (<kbd>ctrl</kbd>+<kbd>7</kbd>).

**Comment by xade93** [comment]
> Does it sort primarily by album and then only within the album sort it by track numbers? Looks like that's what it does in my case.
>

Oh just checked, indeed Quod Libet treats the songs as different albums. I think it's because song of same album name but different author seems to be treated as different albums? Although I can see the rationale behind it, how do I prevent this from happening?

**Comment by Ironbalden** [comment]
Use the albumartist tag, put something like 'Various Artists' and it should be treated as a single album

**Comment by Aldian-fr** [comment]
Hi I have had the same problem for a long time on quodlibet 4.4 with ubuntu 22.04.

Recently I updated to ubuntu 24.04 and tried on quodlibet 4.6 but there seems to be a bug I am the only one to have, which prevents every column sort from working at all. So I reverted to quodlibet 4.4, which was quite difficult since it is not genuinely  compatible with python 3.12, but I somehow worked it out by patching the code with bits I found here and there, mostly about classes moved from collections to collections.abc

**Comment by declension** [comment]
As per comments above I think this is just album detection. Best to use strong metadata around albums (Musicbrainz ones are ideal, or `labelid` etc). 

See https://quodlibet.readthedocs.io/en/latest/guide/faq.html#i-have-two-albums-with-the-same-name-which-are-merged-in-the-album-list

Meanwhile unless there's anything concrete to change, I'm going to close the issue
