### ISSUE TITLE
option for writing rating to media file

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#489]
Original [issue 489](https://code.google.com/p/quodlibet/issues/detail?id=489) created by cdmoore1972 on 2010-04-21T14:28:37.000Z:

I know there is no consistency in how ratings are stored in metadata across
filetypes and media players, but writing the ratings to the metadata would
allow me to make my music files somewhat more portable should I want to
listen to them on Windows . . . or a Mac . . . or my MP3 player.

Could you make &quot;
Write to file:  __ rating  
                __ last played
                __ plays&quot;
an option in the preferences?

Again, I know these are junk fields that will not be of any interest to
other people who might have access to my files, but I also have a huge
collection that is used across multiple media players and platforms.  It
would be a big time saver.  

Chris

**Comment by tiangolo** [comment]
I'm very interested in this feature, specifically, writing ratings to media files.

I see this issue is marked as duplicate and closed, but I can't find the one this duplicates.

I see you moved recently from Bitbucket and maybe that's why there's no reference to the other issue. 

I would like to know what happened, and I know it would be bothering to create another duplicating issue, so, could you please tag that issue here so I can follow it?
