### ISSUE TITLE
Option to leave songs in queue after playback

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#676]
Original [issue 676](https://code.google.com/p/quodlibet/issues/detail?id=676) created by NTICompass on 2011-02-26T18:41:52.000Z:

There should be an option to leave songs in the queue after they have played, so I can press previous to play them again.  I use the queue like a 'now playing' playlist, because I like how the queue is part of the main window.
Or, can the (now playing) playlist be docked in the main window like the queue is?

**Comment by spxxxk** [comment]
One thing bothering me for a while with QL is that secondary browsers are extremely useful to work with, but there's no way to play tracks from them unless using the queue. Since the queue removes played tracks it's not that great for managing listened music. 
One way it could work would be by greying out the played tracks, next track still at the top but old ones available by scrolling up. The queue would function as usual but the user would be allowed to scroll up  and manage (edit, delete ...) old tracks. Double clicking an old track could set the queue to an older state (with following tracks un-greyed out).

**Comment by CreamyCookie** [comment]
@lazka I think this has been fixed with #1890 

(Apparently I missed this older issue at the time.)

**Comment by lazka** [comment]
Thanks

**Comment by CreamyCookie** [comment]
Thanks for the invitation. =)

(I accepted.)
