### ISSUE TITLE
Add file ignore filters for library

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#914]
Original [issue 914](https://code.google.com/p/quodlibet/issues/detail?id=914) created by bfdev@mailworks.org on 2012-02-11T17:09:28.000Z:

This could be a glob expression that would be configured for each (or all?) library folders. Files or sub-folders matching the expression would be ignored when scanning the library.  An expression like &quot;*/.AppleDouble/*&quot; would cause all files located in &quot;AppleDouble&quot; sub-folders under a library folder to be ignored.

I happen to have an issue with AppleDouble files but the filter could be used for excluding any unwanted files.  (AppleDouble files can occur on network shares with Apple client systems.  Scanning the AppleDouble files greatly increases the time it takes for quodlibet to scan the library.)

I tested this idea somewhat by making changes to the &quot;songs.py&quot; file.  
I added the following function:

import fnmatch
def ExcludeFile(fname, patterns):
    for pat in patterns:
        match = fnmatch.fnmatch(fname, pat)
        if match: break
    return match
    
In the scan() function in songs.py I changed the line:

if filter(fullfilename.startswith, exclude):

to 

MyExcludes=['*/.AppleDouble/*']
if filter(fullfilename.startswith, exclude) or \
  ExcludeFile(fullfilename, MyExcludes):

There may be a better way but it had the desired effect.  Obviously, hard coding
the variable &quot;MyExcludes&quot; is not right. I'm not sure how to work this into the
quodlibet configuration system and unfortunately don't have any more time to
spend right now.

**Comment by markshep** [comment]
I've just installed Quod Libet for the first time and scanned my library, but it's polluted with loads of files that I don't want.  That's because all my audio is in a [Resilio Sync](https://getsync.com/) directory and it's picked up old backup files which are stored in the `.sync` subdirectory.

Rather than having user-specified exclude rules a much simpler alternative would be to just exclude any files/directories starting with a `.`.  That fits in with the standard Unix notion of hidden files/directories and would fix the problem in both the `.AppleDouble` and `.sync` use cases.

**Comment by lazka** [comment]
> Rather than having user-specified exclude rules a much simpler alternative would be to just exclude any files/directories starting with a `.`.  That fits in with the standard Unix notion of hidden files/directories and would fix the problem in both the `.AppleDouble` and `.sync` use cases.

Sounds good.

**Comment by markshep** [comment]
See [b215907](https://github.com/markshep/quodlibet/commit/b215907b1e2503533fdd024be7d08f96892648a1) for a quick proof of concept.  This doesn't gracefully handle the user changing the option (i.e. newly excluded dot files won't get purged from the library), but does seem to work on a fresh install if it's enabled before the first scan.

**Comment by lazka** [comment]
Thanks for the proof of concept. Moving this to #2074

**Comment by fgvieira** [comment]
Dear all,

I've only recently discovered `Quod Libet` but I must say it is exactly what I've been looking for! Simple, easy to use and fully customizable.

However, are there any plans to re-open this issue? Since `Quod Libet` is highly customizable, I'd expect it to be possible to ignore certain folders from the library. Ignoring hidden files makes sense, but it would also be nice to be able to manually select some folders to be excluded from the library. Maybe add another box under `Preferences ->Library` to ignore/exclude directories (like the `Scan Directories`).
